/**
 * ServerEditSheet - inline form for editing an existing saved server.
 *
 * Rendered inside a MobileBottomSheet on mobile or as a dialog on desktop.
 * Reuses the glass input style from ConnectPage.
 */

import { useCallback, useEffect, useState, type FormEvent } from "react";
import { invoke } from "@tauri-apps/api/core";
import { useTranslation } from "react-i18next";
import type { SavedServer } from "../../types";
import { getServerPassword, setServerPassword } from "../../serverStorage";
import { isMobile } from "../../utils/platform";
import MobileBottomSheet from "../elements/MobileBottomSheet";
import styles from "./ServerEditSheet.module.css";

interface Props {
  server: SavedServer;
  onSave: (id: string, patch: Partial<Omit<SavedServer, "id">>) => void;
  onClose: () => void;
}

function EditForm({ server, onSave, onClose }: Readonly<Props>) {
  const { t } = useTranslation("server");
  const [label, setLabel] = useState(server.label || "");
  const [host, setHost] = useState(server.host);
  const [port, setPort] = useState(String(server.port));
  const [username, setUsername] = useState(server.username);
  const [password, setPassword] = useState("");
  const [hasStoredPassword, setHasStoredPassword] = useState(false);
  const [clearPassword, setClearPassword] = useState(false);
  const [certLabel, setCertLabel] = useState(server.cert_label ?? "");
  const [availableCerts, setAvailableCerts] = useState<string[]>([]);
  const [creatingCert, setCreatingCert] = useState(false);
  const [newCertName, setNewCertName] = useState("");

  const refreshCerts = useCallback(() => {
    invoke<string[]>("list_certificates")
      .then(setAvailableCerts)
      .catch(() => setAvailableCerts([]));
  }, []);

  useEffect(() => {
    refreshCerts();
    getServerPassword(server.id).then((pw) => {
      if (pw) {
        setHasStoredPassword(true);
      }
    });
  }, [server.id, refreshCerts]);

  const handleCreateCert = async () => {
    const name = newCertName.trim();
    if (!name) return;
    await invoke("generate_certificate", { label: name });
    await refreshCerts();
    setCertLabel(name);
    setNewCertName("");
    setCreatingCert(false);
  };

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();
    if (!host.trim() || !username.trim()) return;

    // Handle password changes: new password takes precedence over clear.
    if (password) {
      await setServerPassword(server.id, password);
    } else if (clearPassword) {
      await setServerPassword(server.id, null);
    }

    onSave(server.id, {
      label: label.trim() || host.trim(),
      host: host.trim(),
      port: Number.parseInt(port) || 64738,
      username: username.trim(),
      cert_label: certLabel || null,
    });
  };

  return (
    <form className={styles.form} onSubmit={handleSubmit}>
      <h3 className={styles.title}>{t("edit.title")}</h3>

      <label className={styles.fieldLabel}>
        {t("edit.labelField")}
        <input
          className={styles.input}
          value={label}
          onChange={(e) => setLabel(e.target.value)}
          placeholder="My Server"
        />
      </label>

      <label className={styles.fieldLabel}>
        {t("edit.hostField")}
        <input
          className={styles.input}
          value={host}
          onChange={(e) => setHost(e.target.value)}
          placeholder="mumble.example.com"
          required
        />
      </label>

      <label className={styles.fieldLabel}>
        {t("edit.portField")}
        <input
          className={styles.input}
          type="number"
          value={port}
          onChange={(e) => setPort(e.target.value)}
          placeholder="64738"
          min={1}
          max={65535}
        />
      </label>

      <label className={styles.fieldLabel}>
        {t("edit.usernameField")}
        <input
          className={styles.input}
          value={username}
          onChange={(e) => setUsername(e.target.value)}
          placeholder="Username"
          required
        />
      </label>

      <label className={styles.fieldLabel}>
        {t("edit.identityField")}
        <select
          className={styles.input}
          value={creatingCert ? "__new__" : certLabel}
          onChange={(e) => {
            if (e.target.value === "__new__") {
              setCreatingCert(true);
            } else {
              setCreatingCert(false);
              setCertLabel(e.target.value);
            }
          }}
        >
          <option value="">{t("edit.certNone")}</option>
          {availableCerts.map((c) => (
            <option key={c} value={c}>
              {c === "default" ? t("edit.certAutoGenerated", { name: c }) : c}
            </option>
          ))}
          <option value="__new__">{t("edit.certCreateNew")}</option>
        </select>
        {creatingCert && (
          <div className={styles.newCertRow}>
            <input
              className={styles.input}
              type="text"
              placeholder={t("edit.identityNamePlaceholder")}
              value={newCertName}
              onChange={(e) => setNewCertName(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === "Enter") {
                  e.preventDefault();
                  handleCreateCert();
                }
              }}
              autoFocus
            />
            <button
              type="button"
              className={styles.cancelBtn}
              onClick={handleCreateCert}
              disabled={!newCertName.trim()}
            >
              {t("edit.createIdentity")}
            </button>
            <button
              type="button"
              className={styles.cancelBtn}
              onClick={() => {
                setCreatingCert(false);
                setNewCertName("");
              }}
            >
              {t("edit.cancelIdentity")}
            </button>
          </div>
        )}
      </label>

      <label className={styles.fieldLabel}>
        {t("edit.passwordField")}
        {hasStoredPassword && !clearPassword ? (
          <div className={styles.storedPassword}>
            <span className={styles.storedLabel}>{t("edit.storedPassword")}</span>
            <button
              type="button"
              className={styles.clearPasswordBtn}
              onClick={() => setClearPassword(true)}
            >
              {t("edit.removePassword")}
            </button>
          </div>
        ) : (
          <input
            className={styles.input}
            type="password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            placeholder={clearPassword ? t("edit.passwordPlaceholderClear") : t("edit.passwordPlaceholderEmpty")}
            autoComplete="new-password"
          />
        )}
      </label>

      <div className={styles.actions}>
        <button type="button" className={styles.cancelBtn} onClick={onClose}>
          {t("edit.cancel")}
        </button>
        <button type="submit" className={styles.saveBtn}>
          {t("edit.save")}
        </button>
      </div>
    </form>
  );
}

export default function ServerEditSheet({ server, onSave, onClose }: Readonly<Props>) {
  if (isMobile) {
    return (
      <MobileBottomSheet open onClose={onClose} ariaLabel="Close server editor">
        <EditForm server={server} onSave={onSave} onClose={onClose} />
      </MobileBottomSheet>
    );
  }

  // Desktop: portal overlay dialog (similar pattern to ConfirmDialog)
  return (
    <div className={styles.overlay} onMouseDown={(e) => { if (e.target === e.currentTarget) onClose(); }}>
      <div className={styles.dialog}>
        <EditForm server={server} onSave={onSave} onClose={onClose} />
      </div>
    </div>
  );
}
