/* AUTO-GENERATED by mumble-tauri/build.rs from constants.json
 * (repo root) - DO NOT EDIT BY HAND. Change constants.json and
 * rebuild; this file will be regenerated automatically.
 */

export const APP_IDENTIFIER = "com.fancymumble.app" as const;
export const UI_MODE_MARKER_FILE = "ui-mode" as const;
export const WEAK_PC_MAX_MEMORY_MB = 4096;
export const WEAK_PC_MAX_CPU_CORES = 2;
export const DEFAULT_SERVER_PORT = 64738;
export const DM_CHANNEL_PREFIX = "__dm:" as const;
export const LOCALES = ["en", "de", "fr", "zh"] as const;
export const DEFAULT_LOCALE = "en" as const;
