// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Audio {
    #[prost(uint32, tag = "3")]
    pub sender_session: u32,
    #[prost(uint64, tag = "4")]
    pub frame_number: u64,
    #[prost(bytes = "vec", tag = "5")]
    pub opus_data: ::prost::alloc::vec::Vec<u8>,
    #[prost(float, repeated, tag = "6")]
    pub positional_data: ::prost::alloc::vec::Vec<f32>,
    #[prost(float, tag = "7")]
    pub volume_adjustment: f32,
    #[prost(bool, tag = "16")]
    pub is_terminator: bool,
    #[prost(oneof = "audio::Header", tags = "1, 2")]
    pub header: ::core::option::Option<audio::Header>,
}
/// Nested message and enum types in `Audio`.
pub mod audio {
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Header {
        #[prost(uint32, tag = "1")]
        Target(u32),
        #[prost(uint32, tag = "2")]
        Context(u32),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Ping {
    #[prost(uint64, tag = "1")]
    pub timestamp: u64,
    #[prost(bool, tag = "2")]
    pub request_extended_information: bool,
    #[prost(uint64, tag = "3")]
    pub server_version_v2: u64,
    #[prost(uint32, tag = "4")]
    pub user_count: u32,
    #[prost(uint32, tag = "5")]
    pub max_user_count: u32,
    #[prost(uint32, tag = "6")]
    pub max_bandwidth_per_user: u32,
    /// Fancy fields start at 1000; upstream owns 1-999 in every upstream
    /// message. Truncated SHA-256 of the server's livery, so the connect screen
    /// can tell a cached copy is current without fetching. Empty means none is
    /// set, and a server that does not send it leaves the client unbranded.
    #[prost(bytes = "vec", tag = "1000")]
    pub livery_digest: ::prost::alloc::vec::Vec<u8>,
}
