// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SessionEnvelope {
    #[prost(oneof = "session_envelope::Body", tags = "1, 2, 3, 4, 5, 6, 7, 8, 9")]
    pub body: ::core::option::Option<session_envelope::Body>,
}
/// Nested message and enum types in `SessionEnvelope`.
pub mod session_envelope {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Body {
        #[prost(message, tag = "1")]
        Hello(super::Hello),
        #[prost(message, tag = "2")]
        Resume(super::ResumeRequest),
        #[prost(message, tag = "3")]
        ResumeAck(super::ResumeAck),
        #[prost(message, tag = "4")]
        Throttled(super::Throttled),
        #[prost(message, tag = "5")]
        VoiceEndpoint(super::VoiceEndpoint),
        #[prost(message, tag = "6")]
        Subscribe(super::LazySubscribe),
        #[prost(message, tag = "7")]
        GreetingOffer(super::GreetingOffer),
        #[prost(message, tag = "8")]
        GreetingWant(super::GreetingWant),
        #[prost(message, tag = "9")]
        GreetingBody(super::GreetingBody),
    }
}
/// The greeting this peer would be sent, named by its hash rather than sent.
///
/// Mumble carries a welcome message as `ServerSync.welcome_text`, which is a
/// string - so a picture inside one has to be a `data:` URI, which is base64 and
/// costs a third more than the picture does, and it has to fit the four
/// kilobytes that string is capped at. The practical effect is that a designed
/// greeting can carry a line icon and nothing else.
///
/// A Fancy client announced itself at `Hello`, so the server knows it can be
/// sent a message rather than a paragraph. This is that message's first half:
/// the greeting changes when an operator edits it, and a peer may join twenty
/// times a day, so what travels first is what *identifies* the document. A
/// client that recognises the hash already has the bytes and says nothing.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GreetingOffer {
    /// SHA-256 of the assembled markup and every asset, ids included.
    #[prost(bytes = "vec", tag = "1")]
    pub digest: ::prost::alloc::vec::Vec<u8>,
    /// What the body would weigh, so a client on a metered link can decline it
    /// rather than discover the size once it is already arriving.
    #[prost(uint32, tag = "2")]
    pub bytes: u32,
}
/// "I do not have that one." Sent only on a cache miss.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GreetingWant {
    /// Echoed from the offer, so a reply that crosses an operator's edit is
    /// recognisably about the older document and can be dropped.
    #[prost(bytes = "vec", tag = "1")]
    pub digest: ::prost::alloc::vec::Vec<u8>,
}
/// The greeting itself.
///
/// Not compressed here: the Fancy wire already zstd's a batch for any client
/// that announced `Hello.zstd`, so a payload compressed at this layer would be
/// compressed twice - and the second pass over already-compressed image bytes
/// spends CPU to make them very slightly bigger.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GreetingBody {
    #[prost(bytes = "vec", tag = "1")]
    pub digest: ::prost::alloc::vec::Vec<u8>,
    /// The assembled markup, carrying `fm-a-<id>` markers where pictures go.
    #[prost(string, tag = "2")]
    pub markup: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub assets: ::prost::alloc::vec::Vec<GreetingAsset>,
}
/// One picture, as bytes.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GreetingAsset {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// `image/webp`, `image/jpeg`, `image/png`, `image/gif`, `image/avif`.
    #[prost(string, tag = "2")]
    pub mime: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "3")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
/// What a Fancy client announces beyond the Version message: the capabilities
/// it actually implements, rather than what its version implies.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Hello {
    #[prost(uint64, tag = "1")]
    pub fancy_version: u64,
    #[prost(bool, tag = "2")]
    pub zstd: bool,
    #[prost(bool, tag = "3")]
    pub resume: bool,
    #[prost(bool, tag = "4")]
    pub lazy_subscribe: bool,
}
/// Replay from a sequence number rather than take the full flood. Legacy
/// clients cannot do this, which is why staggered drain is required regardless
/// docs/ARCHITECTURE.md §5.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ResumeRequest {
    #[prost(string, tag = "1")]
    pub session_token: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub last_seq: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ResumeAck {
    #[prost(bool, tag = "1")]
    pub accepted: bool,
    #[prost(uint64, tag = "2")]
    pub from_seq: u64,
    /// Set when the gap is longer than the replay ring: the client must re-sync
    /// from scratch, and is told so rather than left with a silent hole.
    #[prost(bool, tag = "3")]
    pub full_resync_required: bool,
    #[prost(string, tag = "4")]
    pub session_token: ::prost::alloc::string::String,
}
/// murmur drops a throttled message in silence, which is how a screen-share
/// SDP offer disappeared with nothing in any log. Fancy clients are told.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Throttled {
    #[prost(uint32, tag = "1")]
    pub r#type: u32,
    #[prost(uint32, tag = "2")]
    pub retry_after_ms: u32,
    #[prost(string, tag = "3")]
    pub route: ::prost::alloc::string::String,
}
/// Where to send audio, for deployments where voice is not reachable at the
/// gateway's own address. A legacy client cannot be told this and is pinned to
/// the advertised pod.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VoiceEndpoint {
    #[prost(string, tag = "1")]
    pub host: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub port: u32,
}
/// Mumble broadcasts all channel and user state to everyone; a Fancy client
/// declares what it is looking at and gets only that.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LazySubscribe {
    #[prost(uint32, repeated, tag = "1")]
    pub channels: ::prost::alloc::vec::Vec<u32>,
    #[prost(bool, tag = "2")]
    pub everything: bool,
}
