// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GifsEnvelope {
    #[prost(oneof = "gifs_envelope::Body", tags = "1, 2, 3")]
    pub body: ::core::option::Option<gifs_envelope::Body>,
}
/// Nested message and enum types in `GifsEnvelope`.
pub mod gifs_envelope {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Body {
        #[prost(message, tag = "1")]
        Query(super::GifQuery),
        #[prost(message, tag = "2")]
        Page(super::GifPage),
        #[prost(message, tag = "3")]
        Refused(super::GifRefused),
    }
}
/// "Search the provider for me."
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GifQuery {
    /// Echoed on the answer. A picker with a search box has a request in flight
    /// whenever somebody is still typing, and without a correlation id the slower
    /// answer overwrites the newer one - the same reason `PreviewRequest` and
    /// `audit.Query` carry one.
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    /// Empty means trending, which is what a picker shows before anyone types.
    /// A separate `kind` enum would let a client ask for trending *and* pass a
    /// query, and there is no answer to that.
    #[prost(string, tag = "2")]
    pub query: ::prost::alloc::string::String,
    /// 1-based, as the provider counts. Zero is read as the first page rather
    /// than refused: it is what an uninitialised field looks like, and refusing
    /// the first page over it helps nobody.
    #[prost(uint32, tag = "3")]
    pub page: u32,
}
/// One result.
///
/// Two sizes, because a picker draws a grid of small ones and sends a large
/// one. The URLs point at the provider's CDN, or at this server when
/// `gif_proxy_media` is on; a client renders whatever it is given and never
/// needs to know which, which is what keeps that an operator's decision rather
/// than a client release.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Gif {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub title: ::prost::alloc::string::String,
    /// Full size, for sending.
    #[prost(string, tag = "3")]
    pub url: ::prost::alloc::string::String,
    /// Grid size, for drawing the picker.
    #[prost(string, tag = "4")]
    pub preview_url: ::prost::alloc::string::String,
    #[prost(uint32, tag = "5")]
    pub width: u32,
    #[prost(uint32, tag = "6")]
    pub height: u32,
    #[prost(uint32, tag = "7")]
    pub preview_width: u32,
    #[prost(uint32, tag = "8")]
    pub preview_height: u32,
    /// `image/webp`, `image/gif`. What `url` is, not what `preview_url` is; they
    /// are the same format in every provider shape seen so far.
    #[prost(string, tag = "9")]
    pub mime: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GifPage {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub results: ::prost::alloc::vec::Vec<Gif>,
    /// Which page this is, echoed so a client that changed its mind mid-scroll
    /// can tell an old answer from the one it is waiting for.
    #[prost(uint32, tag = "3")]
    pub page: u32,
    #[prost(bool, tag = "4")]
    pub has_next: bool,
    /// Which provider answered ("klipy"). For attribution, which these APIs
    /// require in their terms, and so a client can say where results came from
    /// rather than implying the server wrote them.
    #[prost(string, tag = "5")]
    pub provider: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GifRefused {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    /// In words a client can show.
    #[prost(string, tag = "2")]
    pub reason: ::prost::alloc::string::String,
    /// How long until a throttled caller may ask again. Zero when waiting is not
    /// what would help. murmur drops a throttled message in silence, which is how
    /// an SDP offer once disappeared with nothing in any log; a client told the
    /// number can say "in a moment" instead of appearing broken.
    #[prost(uint32, tag = "3")]
    pub retry_after_ms: u32,
    #[prost(enumeration = "gif_refused::Reason", tag = "4")]
    pub kind: i32,
}
/// Nested message and enum types in `GifRefused`.
pub mod gif_refused {
    /// Why, in a form a client can branch on.
    ///
    /// The distinction that matters is UNAVAILABLE against everything else: it is
    /// the only one that means *this server does not do this*, and so the only
    /// one on which a client should fall back to a key of its own. Falling back
    /// on THROTTLED would route around the rate limit with the user's own quota,
    /// which is precisely the abuse the limit exists to stop.
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Reason {
        /// No key configured, or the operator has switched the service off.
        Unavailable = 0,
        /// Asking too fast. `retry_after_ms` says how long.
        Throttled = 1,
        /// The provider failed, timed out, or answered something unreadable.
        Upstream = 2,
        /// The query itself cannot be served - too long, or not valid UTF-8.
        Malformed = 3,
    }
    impl Reason {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Unavailable => "UNAVAILABLE",
                Self::Throttled => "THROTTLED",
                Self::Upstream => "UPSTREAM",
                Self::Malformed => "MALFORMED",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "UNAVAILABLE" => Some(Self::Unavailable),
                "THROTTLED" => Some(Self::Throttled),
                "UPSTREAM" => Some(Self::Upstream),
                "MALFORMED" => Some(Self::Malformed),
                _ => None,
            }
        }
    }
}
