// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FilesEnvelope {
    #[prost(oneof = "files_envelope::Body", tags = "1, 2, 3, 4, 5, 6, 7")]
    pub body: ::core::option::Option<files_envelope::Body>,
}
/// Nested message and enum types in `FilesEnvelope`.
pub mod files_envelope {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Body {
        #[prost(message, tag = "1")]
        Upload(super::UploadRequest),
        #[prost(message, tag = "2")]
        Download(super::DownloadRequest),
        #[prost(message, tag = "3")]
        Grant(super::Grant),
        #[prost(message, tag = "4")]
        Share(super::Share),
        #[prost(message, tag = "5")]
        Listing(super::Listing),
        #[prost(message, tag = "6")]
        List(super::ListRequest),
        #[prost(message, tag = "7")]
        Refused(super::Refused),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UploadRequest {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub channel: u32,
    #[prost(string, tag = "3")]
    pub filename: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub content_type: ::prost::alloc::string::String,
    #[prost(uint64, tag = "5")]
    pub size: u64,
    #[prost(bytes = "vec", tag = "6")]
    pub sha256: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DownloadRequest {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub key: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Grant {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub url: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub method: ::prost::alloc::string::String,
    #[prost(uint64, tag = "4")]
    pub expires_at_ms: u64,
    #[prost(string, tag = "5")]
    pub key: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Share {
    #[prost(string, tag = "1")]
    pub key: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub channel: u32,
    #[prost(uint32, tag = "3")]
    pub owner: u32,
    #[prost(string, tag = "4")]
    pub filename: ::prost::alloc::string::String,
    #[prost(uint64, tag = "5")]
    pub size: u64,
    #[prost(uint64, tag = "6")]
    pub shared_at_ms: u64,
    #[prost(bool, tag = "7")]
    pub public: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListRequest {
    #[prost(uint32, tag = "1")]
    pub channel: u32,
    #[prost(uint32, tag = "2")]
    pub limit: u32,
    #[prost(string, tag = "3")]
    pub before_key: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Listing {
    #[prost(uint32, tag = "1")]
    pub channel: u32,
    #[prost(message, repeated, tag = "2")]
    pub files: ::prost::alloc::vec::Vec<Share>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Refused {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub refusal: ::core::option::Option<crate::proto::fancy::wire::Refusal>,
}
