// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InvitesEnvelope {
    #[prost(oneof = "invites_envelope::Body", tags = "1, 2, 3, 4, 5, 6, 7, 8, 9")]
    pub body: ::core::option::Option<invites_envelope::Body>,
}
/// Nested message and enum types in `InvitesEnvelope`.
pub mod invites_envelope {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Body {
        #[prost(message, tag = "1")]
        SupportQuery(super::InviteSupportQuery),
        #[prost(message, tag = "2")]
        Support(super::InviteSupport),
        #[prost(message, tag = "3")]
        Create(super::InviteCreate),
        #[prost(message, tag = "4")]
        Created(super::InviteCreated),
        #[prost(message, tag = "5")]
        ListQuery(super::InviteListQuery),
        #[prost(message, tag = "6")]
        List(super::InviteList),
        #[prost(message, tag = "7")]
        Revoke(super::InviteRevoke),
        #[prost(message, tag = "8")]
        Revoked(super::InviteRevoked),
        #[prost(message, tag = "9")]
        Refused(super::InviteRefused),
    }
}
/// "May I invite people here, and on what terms?" Asked once per connection.
///
/// Answered from configuration and this session's permissions alone. A client
/// draws its "Invite people" entries from the answer, so it has to arrive
/// before anybody opens a menu, and it is re-asked when the settings change.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InviteSupportQuery {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
}
/// The answer to an InviteSupportQuery.
///
/// A server too old to know the question answers nothing at all, which a client
/// reads the same as `available = false`.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InviteSupport {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    /// Whether this server takes invites at all. False when the operator set
    /// `invites = "off"`, in which case no invite admits anybody either.
    #[prost(bool, tag = "2")]
    pub available: bool,
    /// Whether this session may mint one.
    #[prost(bool, tag = "3")]
    pub may_create: bool,
    /// Whether this session may list and revoke everybody's invites rather than
    /// only its own. The same authority that edits the server settings.
    #[prost(bool, tag = "4")]
    pub may_manage: bool,
    /// The longest lifetime an invite may be given, in seconds. Zero: no ceiling.
    #[prost(uint64, tag = "5")]
    pub max_age_s: u64,
    /// The most people one invite may admit. Zero: no ceiling.
    #[prost(uint32, tag = "6")]
    pub max_uses: u32,
    /// `host` or `host:port` a link should name, when the operator set one.
    /// Empty means the address the client dialled, which is right unless the
    /// server sits behind something that makes that address private.
    #[prost(string, tag = "7")]
    pub address: ::prost::alloc::string::String,
    /// Whether an invite admits past the server password. When false an invite
    /// still lands its holder in its channel, but only once they know the
    /// password - which is how an operator uses invites as "go here" links alone.
    #[prost(bool, tag = "8")]
    pub skips_password: bool,
}
/// Mint one.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InviteCreate {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    /// Where the invitee lands. Zero: wherever they would have landed anyway.
    /// The creator must be allowed to enter it.
    #[prost(uint32, tag = "2")]
    pub channel_id: u32,
    /// Seconds from now. Zero asks for the longest the server allows, which is
    /// forever when it sets no ceiling. Longer than the ceiling is clamped to it.
    #[prost(uint64, tag = "3")]
    pub max_age_s: u64,
    /// How many people it admits. Zero asks for the most the server allows,
    /// unlimited when it sets no ceiling. More than the ceiling is clamped.
    #[prost(uint32, tag = "4")]
    pub max_uses: u32,
}
/// One invite, as its creator and the server's administrators see it.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Invite {
    #[prost(string, tag = "1")]
    pub code: ::prost::alloc::string::String,
    /// Zero: no particular channel.
    #[prost(uint32, tag = "2")]
    pub channel_id: u32,
    #[prost(uint64, tag = "3")]
    pub created_ms: u64,
    /// Zero: never.
    #[prost(uint64, tag = "4")]
    pub expires_ms: u64,
    /// Zero: unlimited.
    #[prost(uint32, tag = "5")]
    pub max_uses: u32,
    /// How many distinct people it has admitted. The same person coming back
    /// with the same link is not a second use.
    #[prost(uint32, tag = "6")]
    pub uses: u32,
    /// The name its creator went by when they made it. A label, not an identity.
    #[prost(string, tag = "7")]
    pub creator: ::prost::alloc::string::String,
    /// Whether the asking session is the one who made it, so a client can offer
    /// "revoke" without knowing how the server identifies people.
    #[prost(bool, tag = "8")]
    pub mine: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InviteCreated {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub invite: ::core::option::Option<Invite>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InviteListQuery {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    /// Everybody's rather than the caller's own. Needs `may_manage`.
    #[prost(bool, tag = "2")]
    pub everyone: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InviteList {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    /// Newest first. Expired and used-up invites are not listed: they admit
    /// nobody, and are swept.
    #[prost(message, repeated, tag = "2")]
    pub invites: ::prost::alloc::vec::Vec<Invite>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InviteRevoke {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub code: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InviteRevoked {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub code: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InviteRefused {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(enumeration = "invite_refused::Reason", tag = "2")]
    pub reason: i32,
    /// For the person reading it; never parsed.
    #[prost(string, tag = "3")]
    pub detail: ::prost::alloc::string::String,
}
/// Nested message and enum types in `InviteRefused`.
pub mod invite_refused {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Reason {
        Other = 0,
        /// Invites are off on this server.
        Unavailable = 1,
        /// This session may not do that.
        Permission = 2,
        /// The request does not make sense, e.g. a channel that does not exist.
        Invalid = 3,
        /// No such invite, or not one this session may see.
        NotFound = 4,
        /// This session already holds as many live invites as it may.
        Limit = 5,
    }
    impl Reason {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Other => "OTHER",
                Self::Unavailable => "UNAVAILABLE",
                Self::Permission => "PERMISSION",
                Self::Invalid => "INVALID",
                Self::NotFound => "NOT_FOUND",
                Self::Limit => "LIMIT",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "OTHER" => Some(Self::Other),
                "UNAVAILABLE" => Some(Self::Unavailable),
                "PERMISSION" => Some(Self::Permission),
                "INVALID" => Some(Self::Invalid),
                "NOT_FOUND" => Some(Self::NotFound),
                "LIMIT" => Some(Self::Limit),
                _ => None,
            }
        }
    }
}
