// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VoiceEnvelope {
    #[prost(oneof = "voice_envelope::Body", tags = "1, 2, 3, 4")]
    pub body: ::core::option::Option<voice_envelope::Body>,
}
/// Nested message and enum types in `VoiceEnvelope`.
pub mod voice_envelope {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Body {
        #[prost(message, tag = "1")]
        Listen(super::ListenRequest),
        #[prost(message, tag = "2")]
        Volume(super::ListenerVolume),
        #[prost(message, tag = "3")]
        Stats(super::VoiceStats),
        #[prost(message, tag = "4")]
        Cipher(super::CipherNotice),
    }
}
/// Hear a channel without joining it. Upstream carries listeners inside
/// UserState; the volume adjustment has no upstream field at all.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListenRequest {
    #[prost(uint32, repeated, tag = "1")]
    pub listen: ::prost::alloc::vec::Vec<u32>,
    #[prost(uint32, repeated, tag = "2")]
    pub unlisten: ::prost::alloc::vec::Vec<u32>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ListenerVolume {
    #[prost(uint32, tag = "1")]
    pub channel: u32,
    #[prost(float, tag = "2")]
    pub volume: f32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VoiceStats {
    #[prost(uint32, tag = "1")]
    pub session: u32,
    #[prost(uint32, tag = "2")]
    pub good: u32,
    #[prost(uint32, tag = "3")]
    pub late: u32,
    #[prost(uint32, tag = "4")]
    pub lost: u32,
    #[prost(uint32, tag = "5")]
    pub resync: u32,
    #[prost(bool, tag = "6")]
    pub udp: bool,
}
/// Which cipher the peer was given, so a client can show it rather than infer
/// it from the shape of the key material.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CipherNotice {
    #[prost(string, tag = "1")]
    pub cipher: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TextEnvelope {
    #[prost(oneof = "text_envelope::Body", tags = "1, 2, 3, 4, 5, 6, 7, 8, 9")]
    pub body: ::core::option::Option<text_envelope::Body>,
}
/// Nested message and enum types in `TextEnvelope`.
pub mod text_envelope {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Body {
        #[prost(message, tag = "1")]
        History(super::HistoryRequest),
        #[prost(message, tag = "2")]
        Page(super::HistoryPage),
        #[prost(message, tag = "3")]
        Edit(super::Edit),
        #[prost(message, tag = "4")]
        Delete(super::Delete),
        #[prost(message, tag = "5")]
        Schedule(super::Scheduled),
        #[prost(message, tag = "6")]
        Query(super::ScheduleQuery),
        #[prost(message, tag = "7")]
        List(super::ScheduleList),
        #[prost(message, tag = "8")]
        Cancel(super::ScheduleCancel),
        #[prost(message, tag = "9")]
        Ack(super::ScheduleAck),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HistoryRequest {
    /// Flat for the same reason pchat's is: routing and authorisation read it.
    #[prost(uint32, tag = "1")]
    pub channel: u32,
    #[prost(message, optional, tag = "2")]
    pub page: ::core::option::Option<crate::proto::fancy::wire::Cursor>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StoredMessage {
    #[prost(string, tag = "1")]
    pub message_id: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub channel: u32,
    #[prost(uint32, tag = "3")]
    pub sender: u32,
    #[prost(string, tag = "4")]
    pub sender_name: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub body: ::prost::alloc::string::String,
    #[prost(uint64, tag = "6")]
    pub sent_at_ms: u64,
    #[prost(bool, tag = "7")]
    pub edited: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HistoryPage {
    #[prost(uint32, tag = "1")]
    pub channel: u32,
    #[prost(message, repeated, tag = "2")]
    pub messages: ::prost::alloc::vec::Vec<StoredMessage>,
    #[prost(message, optional, tag = "3")]
    pub page: ::core::option::Option<crate::proto::fancy::wire::PageInfo>,
}
/// Both of these named a message and no channel, which left the service unable
/// to route or authorise one without first looking the id up. `MessageRef`
/// carries the pair, and unlike the fan-out paths above nothing here reads the
/// channel before the body is understood.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Edit {
    #[prost(message, optional, tag = "1")]
    pub target: ::core::option::Option<crate::proto::fancy::wire::MessageRef>,
    #[prost(string, tag = "2")]
    pub body: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Delete {
    #[prost(message, optional, tag = "1")]
    pub target: ::core::option::Option<crate::proto::fancy::wire::MessageRef>,
}
/// Client -> server to schedule; server -> client as the elements of a
/// `ScheduleList`. Every identity and time field below the body is written by
/// the server, so a client that fills one in changes nothing.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Scheduled {
    /// Assigned by the server. A client that sends one is ignored, because an id
    /// a peer chooses is an id a peer can collide with somebody else's.
    #[prost(string, tag = "1")]
    pub schedule_id: ::prost::alloc::string::String,
    /// Where it goes. At least one channel or tree is required, and a tree means
    /// the channel and everything under it, as `TextMessage.tree_id` does.
    #[prost(uint32, repeated, tag = "2")]
    pub channels: ::prost::alloc::vec::Vec<u32>,
    #[prost(uint32, repeated, tag = "3")]
    pub trees: ::prost::alloc::vec::Vec<u32>,
    #[prost(string, tag = "4")]
    pub body: ::prost::alloc::string::String,
    #[prost(uint64, tag = "5")]
    pub deliver_at_ms: u64,
    /// The creator's session when they scheduled it. Delivery attributes the
    /// message to this session only if the same person is still connected, so it
    /// is a display hint and never the owner.
    #[prost(uint32, tag = "6")]
    pub creator: u32,
    /// The owner. A session id is per connection and recycled; only the
    /// certificate still names the same person after a reconnect, which is what
    /// "only the creator may cancel" has to mean.
    #[prost(bytes = "vec", tag = "7")]
    pub creator_cert: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "8")]
    pub creator_name: ::prost::alloc::string::String,
    #[prost(uint64, tag = "9")]
    pub created_at_ms: u64,
    #[prost(enumeration = "ScheduleStatus", tag = "10")]
    pub status: i32,
}
/// Client -> server: the caller's own scheduled messages.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ScheduleQuery {
    /// Include what has already been delivered or cancelled. Pending only by
    /// default, which is what a "pending" panel shows.
    #[prost(bool, tag = "1")]
    pub include_finished: bool,
}
/// Server -> client: the answer to a `ScheduleQuery`.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ScheduleList {
    #[prost(message, repeated, tag = "1")]
    pub messages: ::prost::alloc::vec::Vec<Scheduled>,
}
/// Client -> server: cancel a pending message. Only its creator may.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ScheduleCancel {
    #[prost(string, tag = "1")]
    pub schedule_id: ::prost::alloc::string::String,
}
/// Server -> client: the outcome of a schedule or a cancel.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ScheduleAck {
    #[prost(string, tag = "1")]
    pub schedule_id: ::prost::alloc::string::String,
    #[prost(enumeration = "ScheduleStatus", tag = "2")]
    pub status: i32,
    /// Why it was refused, in words a client can show. Empty otherwise.
    #[prost(string, tag = "3")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ModerationEnvelope {
    #[prost(oneof = "moderation_envelope::Body", tags = "1, 2, 3, 4")]
    pub body: ::core::option::Option<moderation_envelope::Body>,
}
/// Nested message and enum types in `ModerationEnvelope`.
pub mod moderation_envelope {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Body {
        #[prost(message, tag = "1")]
        Ban(super::BanEntry),
        #[prost(message, tag = "2")]
        Bans(super::BanEntries),
        #[prost(message, tag = "3")]
        Unban(super::Unban),
        #[prost(message, tag = "4")]
        Refused(super::Refused),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BanEntry {
    #[prost(uint64, tag = "1")]
    pub id: u64,
    #[prost(string, tag = "2")]
    pub address: ::prost::alloc::string::String,
    #[prost(uint32, tag = "3")]
    pub prefix_len: u32,
    #[prost(string, tag = "4")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub hash: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub reason: ::prost::alloc::string::String,
    #[prost(uint64, tag = "7")]
    pub start_ms: u64,
    #[prost(uint32, tag = "8")]
    pub duration_s: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BanEntries {
    #[prost(message, repeated, tag = "1")]
    pub bans: ::prost::alloc::vec::Vec<BanEntry>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Unban {
    #[prost(uint64, tag = "1")]
    pub id: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Refused {
    #[prost(string, tag = "1")]
    pub action: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub refusal: ::core::option::Option<crate::proto::fancy::wire::Refusal>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PluginsEnvelope {
    #[prost(oneof = "plugins_envelope::Body", tags = "1, 2, 3, 4, 5")]
    pub body: ::core::option::Option<plugins_envelope::Body>,
}
/// Nested message and enum types in `PluginsEnvelope`.
pub mod plugins_envelope {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Body {
        #[prost(message, tag = "1")]
        Registry(super::Registry),
        #[prost(message, tag = "2")]
        Query(super::RegistryQuery),
        #[prost(message, tag = "3")]
        Opaque(super::Opaque),
        #[prost(message, tag = "4")]
        Admin(super::Admin),
        #[prost(message, tag = "5")]
        AdminResult(super::AdminResult),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PluginDescriptor {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub version: ::prost::alloc::string::String,
    #[prost(bool, tag = "4")]
    pub enabled: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Registry {
    #[prost(message, repeated, tag = "1")]
    pub plugins: ::prost::alloc::vec::Vec<PluginDescriptor>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RegistryQuery {}
/// The server never learns what is inside. That is the whole opacity rule, and
/// it is why this is `bytes` and not a oneof of plugin message types.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Opaque {
    #[prost(string, tag = "1")]
    pub plugin: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, repeated, tag = "3")]
    pub recipients: ::prost::alloc::vec::Vec<u32>,
    #[prost(uint32, tag = "4")]
    pub sender: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Admin {
    #[prost(enumeration = "admin::Kind", tag = "1")]
    pub kind: i32,
    #[prost(string, tag = "2")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub source_key: ::prost::alloc::string::String,
}
/// Nested message and enum types in `Admin`.
pub mod admin {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Kind {
        Enable = 0,
        Disable = 1,
        Install = 2,
        Uninstall = 3,
    }
    impl Kind {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Enable => "ENABLE",
                Self::Disable => "DISABLE",
                Self::Install => "INSTALL",
                Self::Uninstall => "UNINSTALL",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "ENABLE" => Some(Self::Enable),
                "DISABLE" => Some(Self::Disable),
                "INSTALL" => Some(Self::Install),
                "UNINSTALL" => Some(Self::Uninstall),
                _ => None,
            }
        }
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AdminResult {
    #[prost(bool, tag = "1")]
    pub ok: bool,
    #[prost(string, tag = "2")]
    pub detail: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PushEnvelope {
    #[prost(oneof = "push_envelope::Body", tags = "1, 2, 3, 4, 5")]
    pub body: ::core::option::Option<push_envelope::Body>,
}
/// Nested message and enum types in `PushEnvelope`.
pub mod push_envelope {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Body {
        #[prost(message, tag = "1")]
        Register(super::Register),
        #[prost(message, tag = "2")]
        Unregister(super::Unregister),
        #[prost(message, tag = "3")]
        Subscribe(super::Subscribe),
        #[prost(message, tag = "4")]
        Ack(super::PushAck),
        #[prost(message, tag = "5")]
        LiveSubscribe(super::LiveSubscribe),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Register {
    #[prost(string, tag = "1")]
    pub token: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub platform: ::prost::alloc::string::String,
    /// The channels to stay quiet about, as `Subscribe.muted`, carried here so a
    /// device that has just registered is not loud until its first subscribe.
    #[prost(uint32, repeated, tag = "3")]
    pub muted: ::prost::alloc::vec::Vec<u32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Unregister {
    #[prost(string, tag = "1")]
    pub token: ::prost::alloc::string::String,
}
/// Which channels a device wants *no* notification from.
///
/// An exclusion list, and the direction matters. This was an inclusion list,
/// `channels` plus an `all` flag, which is the wrong shape twice over: a user
/// mutes two rooms out of forty and cannot be asked to enumerate the other
/// thirty-eight, and any channel created after the list was sent would silently
/// stop notifying. Muting is the thing a person does; being notified is the
/// default they are changing.
///
/// The whole set is replaced on every send, so a client can always say "I have
/// forgotten that one", the same reason `permissions.TokenSet` replaces rather
/// than adds.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Subscribe {
    #[prost(uint32, repeated, tag = "1")]
    pub muted: ::prost::alloc::vec::Vec<u32>,
}
/// "Send me messages from channels I am not in, while I am here."
///
/// The fork's `FancySubscribePush` (wire 125), and a different feature from
/// `Subscribe` above however alike the two look: that one is about a *device*
/// that is asleep, this one is about a *session* that is connected. A subscriber
/// is added to the recipients of a text message addressed at a channel they hold
/// `SubscribePush` in, without joining it and without a listener. It is how a
/// phone that is awake sees the room it has notifications for.
///
/// Session-scoped, so it needs no account and dies with the connection --
/// deliberately, since a subscription that outlived the session would belong to
/// whoever inherits the session id.
///
/// `muted` is an exclusion list, as everywhere else here: the channels to leave
/// out of that delivery, and the whole set is replaced on every send.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LiveSubscribe {
    #[prost(uint32, repeated, tag = "1")]
    pub muted: ::prost::alloc::vec::Vec<u32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PushAck {
    #[prost(bool, tag = "1")]
    pub ok: bool,
    #[prost(string, tag = "2")]
    pub detail: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AuditEnvelope {
    #[prost(oneof = "audit_envelope::Body", tags = "1, 2, 3, 4, 5, 6, 7, 8")]
    pub body: ::core::option::Option<audit_envelope::Body>,
}
/// Nested message and enum types in `AuditEnvelope`.
pub mod audit_envelope {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Body {
        #[prost(message, tag = "1")]
        Query(super::Query),
        #[prost(message, tag = "2")]
        Page(super::Page),
        #[prost(message, tag = "3")]
        Config(super::Config),
        #[prost(message, tag = "4")]
        ConfigUpdate(super::ConfigUpdate),
        #[prost(message, tag = "5")]
        Event(super::Event),
        #[prost(message, tag = "6")]
        ConfigQuery(super::ConfigQuery),
        #[prost(message, tag = "7")]
        Verify(super::Verify),
        #[prost(message, tag = "8")]
        VerifyResult(super::VerifyResult),
    }
}
/// Asks for the Config below. Client-initiated rather than pushed after sync:
/// the admin surface is opened long after the handshake, and a snapshot pushed
/// at sync is one the client has to hold and invalidate for a tab most sessions
/// never open.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ConfigQuery {}
/// Walk the chain and report the first link that does not hold.
///
/// Separate from Query because it is not a search: it reads every row in the
/// scope, so it is an explicit operator action behind its own button rather
/// than something a filter change can trigger.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Verify {
    /// Echoed on VerifyResult, for the reason Query.query_id exists.
    #[prost(string, tag = "1")]
    pub query_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VerifyResult {
    #[prost(bool, tag = "1")]
    pub intact: bool,
    /// How many links held. On a break this is where the walk stopped, which is
    /// the entry *before* the tampered one.
    #[prost(uint64, tag = "2")]
    pub checked: u64,
    /// The first entry whose link does not hold, empty when intact.
    #[prost(string, tag = "3")]
    pub broken_at: ::prost::alloc::string::String,
    /// The `Verify.query_id` this answers.
    #[prost(string, tag = "4")]
    pub query_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Query {
    #[prost(uint64, tag = "1")]
    pub since_ms: u64,
    #[prost(uint64, tag = "2")]
    pub until_ms: u64,
    #[prost(string, tag = "3")]
    pub category: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub page: ::core::option::Option<crate::proto::fancy::wire::Cursor>,
    /// Narrow to what was done to one account. Indexed
    /// (`ix_audit_target`), which is why this is offered as a filter and
    /// `target_channel` below is not: a filter that table-scans the log is a
    /// way to make the server slow from a chat window.
    #[prost(uint64, tag = "5")]
    pub target_account: u64,
    /// Echoed on the reply. A client shows one audit tab but a filter change and
    /// a page-down are two queries in flight, and without a correlation id the
    /// slower one's page overwrites the newer one's. Same reason
    /// `PreviewRequest.request_id` exists.
    #[prost(string, tag = "6")]
    pub query_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AuditRecord {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub at_ms: u64,
    #[prost(string, tag = "3")]
    pub category: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub action: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub actor: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub detail: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub entry_hash: ::prost::alloc::string::String,
    /// Who and where it was done to. The store has held both since it existed and
    /// the record dropped them, so "banned" arrived without saying whom, and a
    /// reader had to parse `detail` (prose written for a human) to find out.
    #[prost(uint64, tag = "8")]
    pub target_account: u64,
    #[prost(uint32, tag = "9")]
    pub target_channel: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Page {
    #[prost(message, repeated, tag = "1")]
    pub records: ::prost::alloc::vec::Vec<AuditRecord>,
    #[prost(message, optional, tag = "2")]
    pub page: ::core::option::Option<crate::proto::fancy::wire::PageInfo>,
    /// The `Query.query_id` this answers.
    #[prost(string, tag = "3")]
    pub query_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Config {
    #[prost(bool, tag = "1")]
    pub enabled: bool,
    #[prost(string, repeated, tag = "2")]
    pub categories: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(uint32, tag = "3")]
    pub retention_days: u32,
    /// How many entries the chain holds, for the config half's chain-status card.
    /// Sent with the config so the card can render a height before anybody asks
    /// for a verify, which is the expensive part.
    #[prost(uint64, tag = "4")]
    pub chain_height: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ConfigUpdate {
    #[prost(message, optional, tag = "1")]
    pub config: ::core::option::Option<Config>,
}
/// Pushed live to an admin watching the log, rather than polled.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Event {
    #[prost(message, optional, tag = "1")]
    pub record: ::core::option::Option<AuditRecord>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OnboardingEnvelope {
    #[prost(oneof = "onboarding_envelope::Body", tags = "1, 2, 3, 4")]
    pub body: ::core::option::Option<onboarding_envelope::Body>,
}
/// Nested message and enum types in `OnboardingEnvelope`.
pub mod onboarding_envelope {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Body {
        #[prost(message, tag = "1")]
        Flow(super::Flow),
        #[prost(message, tag = "2")]
        Query(super::FlowQuery),
        #[prost(message, tag = "3")]
        Response(super::Response),
        #[prost(message, tag = "4")]
        Update(super::FlowUpdate),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Step {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub title: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub body: ::prost::alloc::string::String,
    #[prost(enumeration = "step::Kind", tag = "4")]
    pub kind: i32,
    #[prost(bool, tag = "5")]
    pub required: bool,
    #[prost(message, repeated, tag = "6")]
    pub choices: ::prost::alloc::vec::Vec<step::Choice>,
    /// Asked before the user may enter a channel at all, rather than at leisure
    /// afterwards. murmur has no such gate, so a stock client never sees one.
    #[prost(bool, tag = "7")]
    pub before_join: bool,
    #[prost(bool, tag = "8")]
    pub multi_select: bool,
}
/// Nested message and enum types in `Step`.
pub mod step {
    /// One selectable answer, and what choosing it grants.
    ///
    /// The grants are the feature. An onboarding answer is not a survey datum: it
    /// is a request for channel visibility and group membership that the server
    /// applies on submission, which is why a shape carrying only a label would
    /// make the whole questionnaire decorative.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct Choice {
        #[prost(string, tag = "1")]
        pub id: ::prost::alloc::string::String,
        #[prost(string, tag = "2")]
        pub label: ::prost::alloc::string::String,
        #[prost(string, tag = "3")]
        pub description: ::prost::alloc::string::String,
        /// Rendered beside the label. A Unicode grapheme cluster, deliberately not
        /// `wire.Emoji`, because a server shortcode would have to resolve against a
        /// custom-emoji set the onboarding flow is shown before the client has.
        #[prost(string, tag = "4")]
        pub emoji: ::prost::alloc::string::String,
        /// Channels this answer reveals to the user...
        #[prost(uint32, repeated, tag = "5")]
        pub channels: ::prost::alloc::vec::Vec<u32>,
        /// ...and the ACL groups it joins them to.
        #[prost(string, repeated, tag = "6")]
        pub groups: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    }
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Kind {
        Info = 0,
        Consent = 1,
        Choice = 2,
        Text = 3,
    }
    impl Kind {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Info => "INFO",
                Self::Consent => "CONSENT",
                Self::Choice => "CHOICE",
                Self::Text => "TEXT",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "INFO" => Some(Self::Info),
                "CONSENT" => Some(Self::Consent),
                "CHOICE" => Some(Self::Choice),
                "TEXT" => Some(Self::Text),
                _ => None,
            }
        }
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Flow {
    #[prost(string, tag = "1")]
    pub flow_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub steps: ::prost::alloc::vec::Vec<Step>,
    #[prost(uint64, tag = "3")]
    pub version: u64,
    /// Off means no client shows the flow. Kept rather than deleting the flow, so
    /// an operator can turn it off without losing what they wrote.
    #[prost(bool, tag = "4")]
    pub enabled: bool,
    /// Granted to everyone who arrives, whatever they answer.
    #[prost(uint32, repeated, tag = "5")]
    pub default_channels: ::prost::alloc::vec::Vec<u32>,
    /// Who last changed it, and when. Server-filled; ignored as input.
    #[prost(string, tag = "6")]
    pub updated_by: ::prost::alloc::string::String,
    #[prost(uint64, tag = "7")]
    pub updated_at_ms: u64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FlowQuery {
    /// Also send back this user's own stored answers.
    #[prost(bool, tag = "1")]
    pub include_answers: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Response {
    #[prost(string, tag = "1")]
    pub flow_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub answers: ::prost::alloc::vec::Vec<response::Answer>,
    /// The flow version these answers were given against. What decides whether to
    /// ask again: an admin who adds a question has a flow nobody has answered,
    /// and without this the server cannot tell that from everybody having.
    #[prost(uint64, tag = "3")]
    pub flow_version: u64,
    /// Server-filled. **Zero means nothing is stored**, the reply to a query from
    /// a user who has never answered, which is a different thing from a user who
    /// answered and chose nothing.
    #[prost(uint64, tag = "4")]
    pub submitted_at_ms: u64,
}
/// Nested message and enum types in `Response`.
pub mod response {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct Answer {
        #[prost(string, tag = "1")]
        pub step_id: ::prost::alloc::string::String,
        /// The `Choice.id`s picked. A TEXT step carries `text` instead.
        #[prost(string, repeated, tag = "2")]
        pub choice_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
        #[prost(string, tag = "3")]
        pub text: ::prost::alloc::string::String,
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FlowUpdate {
    #[prost(message, optional, tag = "1")]
    pub flow: ::core::option::Option<Flow>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LinkPreviewEnvelope {
    #[prost(oneof = "link_preview_envelope::Body", tags = "1, 2, 3")]
    pub body: ::core::option::Option<link_preview_envelope::Body>,
}
/// Nested message and enum types in `LinkPreviewEnvelope`.
pub mod link_preview_envelope {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Body {
        #[prost(message, tag = "1")]
        Request(super::PreviewRequest),
        #[prost(message, tag = "2")]
        Preview(super::Preview),
        #[prost(message, tag = "3")]
        Error(super::PreviewError),
    }
}
/// "Preview these links for me."
///
/// **Several URLs, one request.** A chat message carries as many links as
/// somebody typed, and a canon that took one per request would have the client
/// either send N frames - through a rate limiter that counts frames - or drop
/// all but the first, which is what the epoch-0 translation did.
///
/// The answers come back one `Preview` (or `PreviewError`) per URL, each
/// carrying the `request_id` and its own `url`, so a client can render them as
/// they arrive rather than waiting for the slowest host in the message.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PreviewRequest {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub urls: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// Fetched by the server, never by the client, so a chat link cannot be used to
/// probe a viewer's network. The fetch is SSRF-guarded on the server side.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Preview {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub url: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub title: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub image_key: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub site: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PreviewError {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ContextActionsEnvelope {
    #[prost(oneof = "context_actions_envelope::Body", tags = "1, 2")]
    pub body: ::core::option::Option<context_actions_envelope::Body>,
}
/// Nested message and enum types in `ContextActionsEnvelope`.
pub mod context_actions_envelope {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Body {
        #[prost(message, tag = "1")]
        Action(super::Action),
        #[prost(message, tag = "2")]
        Menu(super::Menu),
    }
}
/// The Fancy half of upstream's ContextAction (17): an action a plugin added,
/// carrying which plugin owns it so the trigger routes back without the server
/// knowing what it does.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Action {
    #[prost(string, tag = "1")]
    pub action: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub plugin: ::prost::alloc::string::String,
    #[prost(uint32, tag = "3")]
    pub session: u32,
    #[prost(uint32, tag = "4")]
    pub channel: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MenuEntry {
    #[prost(string, tag = "1")]
    pub action: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub text: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub plugin: ::prost::alloc::string::String,
    #[prost(uint32, tag = "4")]
    pub context: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Menu {
    #[prost(message, repeated, tag = "1")]
    pub entries: ::prost::alloc::vec::Vec<MenuEntry>,
    #[prost(string, repeated, tag = "2")]
    pub removed: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// What a scheduled message is doing.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ScheduleStatus {
    SchedulePending = 0,
    ScheduleDelivered = 1,
    ScheduleCancelled = 2,
    /// Never stored: the schedule was refused, and the ack says why.
    ScheduleRefused = 3,
}
impl ScheduleStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::SchedulePending => "SCHEDULE_PENDING",
            Self::ScheduleDelivered => "SCHEDULE_DELIVERED",
            Self::ScheduleCancelled => "SCHEDULE_CANCELLED",
            Self::ScheduleRefused => "SCHEDULE_REFUSED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SCHEDULE_PENDING" => Some(Self::SchedulePending),
            "SCHEDULE_DELIVERED" => Some(Self::ScheduleDelivered),
            "SCHEDULE_CANCELLED" => Some(Self::ScheduleCancelled),
            "SCHEDULE_REFUSED" => Some(Self::ScheduleRefused),
            _ => None,
        }
    }
}
