// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SocialEnvelope {
    #[prost(oneof = "social_envelope::Body", tags = "1, 2, 3, 4, 5, 6, 7, 8, 9, 10")]
    pub body: ::core::option::Option<social_envelope::Body>,
}
/// Nested message and enum types in `SocialEnvelope`.
pub mod social_envelope {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Body {
        #[prost(message, tag = "1")]
        Reaction(super::Reaction),
        #[prost(message, tag = "2")]
        Typing(super::Typing),
        #[prost(message, tag = "3")]
        Receipt(super::ReadReceipt),
        #[prost(message, tag = "4")]
        Poll(super::Poll),
        #[prost(message, tag = "5")]
        Vote(super::PollVote),
        #[prost(message, tag = "6")]
        PollState(super::PollState),
        #[prost(message, tag = "7")]
        Watch(super::WatchSync),
        #[prost(message, tag = "8")]
        WatchState(super::WatchState),
        #[prost(message, tag = "9")]
        Stroke(super::DrawStroke),
        #[prost(message, tag = "10")]
        Clear(super::DrawClear),
    }
}
/// The one reaction message. pchat carried a second, weaker one until the
/// epoch-1 canon settled (docs/PROTOCOL-REDESIGN.md §2).
///
/// `channel` and `message_id` stay flat rather than folding into a
/// `wire.MessageRef`: this is the fan-out address the service reads on every
/// reaction, and nesting it would put an "absent" case in front of a field
/// routing cannot do without.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Reaction {
    #[prost(uint32, tag = "1")]
    pub channel: u32,
    #[prost(string, tag = "2")]
    pub message_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub emoji: ::core::option::Option<crate::proto::fancy::wire::Emoji>,
    #[prost(uint32, tag = "4")]
    pub actor: u32,
    #[prost(bool, tag = "5")]
    pub remove: bool,
    /// The actor's leaf certificate, written by the server on relay.
    ///
    /// `actor` is a session id, which is per connection and recycled, and a
    /// receiver keys reactions per reactor so it can render "you reacted" and
    /// undo the right one. With no durable identity on the wire every reactor
    /// collapsed into one, so two people reacting counted once and either one
    /// removing it removed both. murmur carries the same hash for the same
    /// reason (`PersistentChatManager.cpp:1461`). Empty for a peer that
    /// presented no certificate.
    #[prost(bytes = "vec", tag = "6")]
    pub actor_cert: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Typing {
    #[prost(uint32, tag = "1")]
    pub channel: u32,
    #[prost(uint32, tag = "2")]
    pub actor: u32,
    #[prost(bool, tag = "3")]
    pub typing: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReadReceipt {
    #[prost(uint32, tag = "1")]
    pub channel: u32,
    #[prost(string, tag = "2")]
    pub message_id: ::prost::alloc::string::String,
    #[prost(uint32, tag = "3")]
    pub actor: u32,
    #[prost(uint64, tag = "4")]
    pub at_ms: u64,
    /// The reader's certificate hash, written by the server on relay - the same
    /// reason `Reaction.actor_cert` exists: a receiver keys read watermarks per
    /// reader, and a session id is recycled. Empty for a peer that presented no
    /// certificate.
    #[prost(bytes = "vec", tag = "5")]
    pub actor_cert: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Poll {
    #[prost(string, tag = "1")]
    pub poll_id: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub channel: u32,
    #[prost(string, tag = "3")]
    pub question: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "4")]
    pub options: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(bool, tag = "5")]
    pub multiple: bool,
    #[prost(uint64, tag = "6")]
    pub closes_at_ms: u64,
    #[prost(uint32, tag = "7")]
    pub creator: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PollVote {
    #[prost(string, tag = "1")]
    pub poll_id: ::prost::alloc::string::String,
    #[prost(uint32, repeated, tag = "2")]
    pub options: ::prost::alloc::vec::Vec<u32>,
    #[prost(uint32, tag = "3")]
    pub voter: u32,
    /// The poll's channel, written by the server on relay.
    ///
    /// A vote used to carry only the poll id, on the reasoning that the poll id
    /// identifies everything about it. It does not identify where to *put* it: a
    /// receiver holds polls per channel, so a vote with no channel is one it
    /// cannot route and drops. The server has the channel from the poll and is
    /// the only party that cannot get it wrong.
    #[prost(uint32, tag = "4")]
    pub channel: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PollState {
    #[prost(message, optional, tag = "1")]
    pub poll: ::core::option::Option<Poll>,
    #[prost(uint32, repeated, tag = "2")]
    pub tallies: ::prost::alloc::vec::Vec<u32>,
    #[prost(bool, tag = "3")]
    pub closed: bool,
}
/// Watch-together: a host drives, everyone else follows. The host is explicit
/// because a transfer has to be observable - a silent one desyncs every viewer.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WatchSync {
    #[prost(string, tag = "1")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub channel: u32,
    #[prost(enumeration = "watch_sync::Kind", tag = "3")]
    pub kind: i32,
    #[prost(string, tag = "4")]
    pub url: ::prost::alloc::string::String,
    #[prost(double, tag = "5")]
    pub position_s: f64,
    #[prost(bool, tag = "6")]
    pub playing: bool,
    #[prost(uint32, tag = "7")]
    pub actor: u32,
    #[prost(uint32, tag = "8")]
    pub new_host: u32,
}
/// Nested message and enum types in `WatchSync`.
pub mod watch_sync {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Kind {
        Start = 0,
        Join = 1,
        Leave = 2,
        State = 3,
        End = 4,
        TransferHost = 5,
    }
    impl Kind {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Start => "START",
                Self::Join => "JOIN",
                Self::Leave => "LEAVE",
                Self::State => "STATE",
                Self::End => "END",
                Self::TransferHost => "TRANSFER_HOST",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "START" => Some(Self::Start),
                "JOIN" => Some(Self::Join),
                "LEAVE" => Some(Self::Leave),
                "STATE" => Some(Self::State),
                "END" => Some(Self::End),
                "TRANSFER_HOST" => Some(Self::TransferHost),
                _ => None,
            }
        }
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WatchState {
    #[prost(string, tag = "1")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub channel: u32,
    #[prost(uint32, tag = "3")]
    pub host: u32,
    #[prost(uint32, repeated, tag = "4")]
    pub viewers: ::prost::alloc::vec::Vec<u32>,
    #[prost(string, tag = "5")]
    pub url: ::prost::alloc::string::String,
    #[prost(double, tag = "6")]
    pub position_s: f64,
    #[prost(bool, tag = "7")]
    pub playing: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DrawStroke {
    #[prost(uint32, tag = "1")]
    pub channel: u32,
    #[prost(uint32, tag = "2")]
    pub actor: u32,
    #[prost(string, tag = "3")]
    pub colour: ::prost::alloc::string::String,
    #[prost(float, tag = "4")]
    pub width: f32,
    /// Flat x,y pairs. Bounded before it is stored: an unbounded point list from
    /// an unauthenticated peer is an allocation attack.
    #[prost(float, repeated, tag = "5")]
    pub points: ::prost::alloc::vec::Vec<f32>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DrawClear {
    #[prost(uint32, tag = "1")]
    pub channel: u32,
    #[prost(uint32, tag = "2")]
    pub actor: u32,
}
