// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SessionEnvelope {
    #[prost(oneof = "session_envelope::Body", tags = "1, 2, 3, 4, 5, 6")]
    pub body: ::core::option::Option<session_envelope::Body>,
}
/// Nested message and enum types in `SessionEnvelope`.
pub mod session_envelope {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Body {
        #[prost(message, tag = "1")]
        Hello(super::Hello),
        #[prost(message, tag = "2")]
        Resume(super::ResumeRequest),
        #[prost(message, tag = "3")]
        ResumeAck(super::ResumeAck),
        #[prost(message, tag = "4")]
        Throttled(super::Throttled),
        #[prost(message, tag = "5")]
        VoiceEndpoint(super::VoiceEndpoint),
        #[prost(message, tag = "6")]
        Subscribe(super::LazySubscribe),
    }
}
/// What a Fancy client announces beyond the Version message: the capabilities
/// it actually implements, rather than what its version implies.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Hello {
    #[prost(uint64, tag = "1")]
    pub fancy_version: u64,
    #[prost(bool, tag = "2")]
    pub zstd: bool,
    #[prost(bool, tag = "3")]
    pub resume: bool,
    #[prost(bool, tag = "4")]
    pub lazy_subscribe: bool,
}
/// Replay from a sequence number rather than take the full flood. Legacy
/// clients cannot do this, which is why staggered drain is required regardless
/// — docs/ARCHITECTURE.md §5.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ResumeRequest {
    #[prost(string, tag = "1")]
    pub session_token: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub last_seq: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ResumeAck {
    #[prost(bool, tag = "1")]
    pub accepted: bool,
    #[prost(uint64, tag = "2")]
    pub from_seq: u64,
    /// Set when the gap is longer than the replay ring: the client must re-sync
    /// from scratch, and is told so rather than left with a silent hole.
    #[prost(bool, tag = "3")]
    pub full_resync_required: bool,
    #[prost(string, tag = "4")]
    pub session_token: ::prost::alloc::string::String,
}
/// murmur drops a throttled message in silence, which is how a screen-share
/// SDP offer disappeared with nothing in any log. Fancy clients are told.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Throttled {
    #[prost(uint32, tag = "1")]
    pub r#type: u32,
    #[prost(uint32, tag = "2")]
    pub retry_after_ms: u32,
    #[prost(string, tag = "3")]
    pub route: ::prost::alloc::string::String,
}
/// Where to send audio, for deployments where voice is not reachable at the
/// gateway's own address. A legacy client cannot be told this and is pinned to
/// the advertised pod.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VoiceEndpoint {
    #[prost(string, tag = "1")]
    pub host: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub port: u32,
}
/// Mumble broadcasts all channel and user state to everyone; a Fancy client
/// declares what it is looking at and gets only that.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LazySubscribe {
    #[prost(uint32, repeated, tag = "1")]
    pub channels: ::prost::alloc::vec::Vec<u32>,
    #[prost(bool, tag = "2")]
    pub everything: bool,
}
