// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ScreenshareEnvelope {
    #[prost(oneof = "screenshare_envelope::Body", tags = "1, 2, 3, 4, 5, 6")]
    pub body: ::core::option::Option<screenshare_envelope::Body>,
}
/// Nested message and enum types in `ScreenshareEnvelope`.
pub mod screenshare_envelope {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Body {
        #[prost(message, tag = "1")]
        Offer(super::Offer),
        #[prost(message, tag = "2")]
        Answer(super::Answer),
        #[prost(message, tag = "3")]
        Start(super::Start),
        #[prost(message, tag = "4")]
        Stop(super::Stop),
        #[prost(message, tag = "5")]
        Viewers(super::Viewers),
        #[prost(message, tag = "6")]
        Health(super::Health),
    }
}
/// The SFU is ICE-lite: it ignores trickled candidates and its own ride in the
/// answer. Never trickle ICE through the control plane — that is a contract
/// constraint, and each half of it cost a debugging session.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Offer {
    #[prost(string, tag = "1")]
    pub share_id: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub channel: u32,
    #[prost(string, tag = "3")]
    pub sdp: ::prost::alloc::string::String,
    /// Offers retry until answered, because the control plane rate-limits and a
    /// silently dropped offer looks exactly like a client bug.
    #[prost(uint32, tag = "4")]
    pub attempt: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Answer {
    #[prost(string, tag = "1")]
    pub share_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub sdp: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub sfu_host: ::prost::alloc::string::String,
    #[prost(uint32, tag = "4")]
    pub sfu_port: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Start {
    #[prost(string, tag = "1")]
    pub share_id: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub channel: u32,
    #[prost(uint32, tag = "3")]
    pub presenter: u32,
    #[prost(string, tag = "4")]
    pub title: ::prost::alloc::string::String,
    #[prost(uint32, tag = "5")]
    pub width: u32,
    #[prost(uint32, tag = "6")]
    pub height: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Stop {
    #[prost(string, tag = "1")]
    pub share_id: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub actor: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Viewers {
    #[prost(string, tag = "1")]
    pub share_id: ::prost::alloc::string::String,
    #[prost(uint32, repeated, tag = "2")]
    pub sessions: ::prost::alloc::vec::Vec<u32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Health {
    #[prost(string, tag = "1")]
    pub share_id: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub fps: u32,
    #[prost(uint32, tag = "3")]
    pub kbps: u32,
    #[prost(uint32, tag = "4")]
    pub dropped: u32,
}
