// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PchatEnvelope {
    #[prost(
        oneof = "pchat_envelope::Body",
        tags = "1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12"
    )]
    pub body: ::core::option::Option<pchat_envelope::Body>,
}
/// Nested message and enum types in `PchatEnvelope`.
pub mod pchat_envelope {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Body {
        #[prost(message, tag = "1")]
        Message(super::Message),
        #[prost(message, tag = "2")]
        Fetch(super::Fetch),
        #[prost(message, tag = "3")]
        FetchResponse(super::FetchResponse),
        #[prost(message, tag = "4")]
        Ack(super::Ack),
        #[prost(message, tag = "5")]
        KeyAnnounce(super::KeyAnnounce),
        #[prost(message, tag = "6")]
        KeyRequest(super::KeyRequest),
        #[prost(message, tag = "7")]
        KeyDeliver(super::KeyDeliver),
        #[prost(message, tag = "8")]
        HolderReport(super::HolderReport),
        #[prost(message, tag = "9")]
        HolderQuery(super::HolderQuery),
        #[prost(message, tag = "10")]
        Pin(super::Pin),
        #[prost(message, tag = "11")]
        PinList(super::PinList),
        #[prost(message, tag = "12")]
        Delete(super::Delete),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Message {
    /// UUIDv7 as a string on the wire, kept as 16 bytes in storage - the wire
    /// type does not change (docs/STORAGE.md L3).
    #[prost(string, tag = "1")]
    pub message_id: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub channel: u32,
    /// Who sent it, *while they are connected*. Server-stamped, and useful for
    /// addressing a live reply - but not an identity, because session ids are
    /// handed out per connection and reused.
    #[prost(uint32, tag = "3")]
    pub sender: u32,
    #[prost(bytes = "vec", tag = "4")]
    pub ciphertext: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "5")]
    pub sent_at_ms: u64,
    #[prost(string, tag = "6")]
    pub supersedes: ::prost::alloc::string::String,
    #[prost(uint32, tag = "7")]
    pub epoch: u32,
    /// Who sent it, durably: the SHA-1 of their leaf certificate.
    ///
    /// **Server-stamped from the TLS connection, never read from the client.**
    /// That is what makes it an identity rather than a claim - a client cannot
    /// attribute a message to somebody else, and the recipient's crypto verifies
    /// against the key announced for this same hash.
    ///
    /// It exists because `sender` cannot carry the archive. A stored message
    /// outlives the connection that produced it, and a session id is recycled, so
    /// an archive keyed on one attributes yesterday's messages to whoever holds
    /// the number today. The client's key ladder is keyed on this hash for the
    /// same reason (`peer_keys`, channel originators, key holders).
    ///
    /// Empty for a peer that presented no certificate; such a peer cannot take
    /// part in the key ladder anyway.
    #[prost(bytes = "vec", tag = "8")]
    pub sender_cert: ::prost::alloc::vec::Vec<u8>,
    /// SHA-256(epoch_key)\[0..8\]. Identifies the exact key, and is what the
    /// client's consensus code compares when two distributions disagree.
    #[prost(bytes = "vec", tag = "9")]
    pub epoch_fingerprint: ::prost::alloc::vec::Vec<u8>,
    /// Position in the sender's chain, for ordering within an epoch.
    #[prost(uint32, tag = "10")]
    pub chain_index: u32,
    /// Which end-to-end scheme sealed it. Per message rather than per channel
    /// because a channel's setting can change while messages sealed under the old
    /// one are still in the archive, and those stay readable.
    #[prost(enumeration = "Protocol", tag = "11")]
    pub protocol: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Fetch {
    /// Flat, not inside the cursor: this is the routing and authorisation
    /// address, and the service reads it on every fetch.
    #[prost(uint32, tag = "1")]
    pub channel: u32,
    #[prost(message, optional, tag = "2")]
    pub page: ::core::option::Option<crate::proto::fancy::wire::Cursor>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FetchResponse {
    #[prost(uint32, tag = "1")]
    pub channel: u32,
    #[prost(message, repeated, tag = "2")]
    pub messages: ::prost::alloc::vec::Vec<Message>,
    #[prost(uint64, tag = "3")]
    pub total_stored: u64,
    #[prost(message, optional, tag = "4")]
    pub page: ::core::option::Option<crate::proto::fancy::wire::PageInfo>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Ack {
    #[prost(string, tag = "1")]
    pub message_id: ::prost::alloc::string::String,
    #[prost(enumeration = "ack::Status", tag = "2")]
    pub status: i32,
    #[prost(string, tag = "3")]
    pub detail: ::prost::alloc::string::String,
}
/// Nested message and enum types in `Ack`.
pub mod ack {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Status {
        Stored = 0,
        Duplicate = 1,
        Refused = 2,
        RateLimited = 3,
    }
    impl Status {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Stored => "STORED",
                Self::Duplicate => "DUPLICATE",
                Self::Refused => "REFUSED",
                Self::RateLimited => "RATE_LIMITED",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "STORED" => Some(Self::Stored),
                "DUPLICATE" => Some(Self::Duplicate),
                "REFUSED" => Some(Self::Refused),
                "RATE_LIMITED" => Some(Self::RateLimited),
                _ => None,
            }
        }
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct KeyAnnounce {
    #[prost(uint32, tag = "1")]
    pub channel: u32,
    #[prost(uint32, tag = "2")]
    pub epoch: u32,
    #[prost(bytes = "vec", tag = "3")]
    pub public_key: ::prost::alloc::vec::Vec<u8>,
    /// Whose key this is. Refused unless it is the sender's own certificate.
    #[prost(bytes = "vec", tag = "4")]
    pub holder_cert: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct KeyRequest {
    #[prost(uint32, tag = "1")]
    pub channel: u32,
    #[prost(uint32, tag = "2")]
    pub epoch: u32,
    #[prost(bytes = "vec", tag = "3")]
    pub requester_key: ::prost::alloc::vec::Vec<u8>,
    /// Who is asking, so a distributor knows which identity to seal to. Refused
    /// unless it is the sender's own certificate.
    #[prost(bytes = "vec", tag = "4")]
    pub requester_cert: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct KeyDeliver {
    #[prost(uint32, tag = "1")]
    pub channel: u32,
    #[prost(uint32, tag = "2")]
    pub epoch: u32,
    /// Where to send it. A session, because this is the one arm the server
    /// unicasts and routing needs a live connection.
    #[prost(uint32, tag = "3")]
    pub recipient: u32,
    #[prost(bytes = "vec", tag = "4")]
    pub sealed_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "5")]
    pub countersignature: ::prost::alloc::vec::Vec<u8>,
    /// Who it was sealed *for*, which is not the same question as where to send
    /// it - and the difference is a real race: the requester can disconnect
    /// between asking and being answered, and a recycled session id would hand
    /// the reply to whoever holds that number now. The recipient compares this
    /// against its own certificate and discards a delivery meant for somebody
    /// else, which it cannot do from a session id alone.
    #[prost(bytes = "vec", tag = "6")]
    pub recipient_cert: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HolderReport {
    #[prost(uint32, tag = "1")]
    pub channel: u32,
    #[prost(uint32, tag = "2")]
    pub epoch: u32,
    #[prost(bytes = "vec", repeated, tag = "3")]
    pub holder_certs: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HolderQuery {
    #[prost(uint32, tag = "1")]
    pub channel: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Pin {
    #[prost(string, tag = "1")]
    pub message_id: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub channel: u32,
    #[prost(bool, tag = "3")]
    pub unpin: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PinList {
    #[prost(uint32, tag = "1")]
    pub channel: u32,
    #[prost(message, repeated, tag = "2")]
    pub pinned: ::prost::alloc::vec::Vec<Message>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Delete {
    #[prost(uint32, tag = "1")]
    pub channel: u32,
    #[prost(string, repeated, tag = "2")]
    pub message_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// The end-to-end schemes a message can be sealed under.
///
/// The server never acts on this - it cannot read any of them - but it is on the
/// wire because the recipient has to know which one to try.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Protocol {
    Unspecified = 0,
    /// Readable from the point of joining onward.
    FancyV1PostJoin = 1,
    /// The whole archive, re-keyed to each new member.
    FancyV1FullArchive = 2,
    /// Not end-to-end at all: the server holds the key.
    ServerManaged = 3,
    SignalV1 = 4,
}
impl Protocol {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "PROTOCOL_UNSPECIFIED",
            Self::FancyV1PostJoin => "FANCY_V1_POST_JOIN",
            Self::FancyV1FullArchive => "FANCY_V1_FULL_ARCHIVE",
            Self::ServerManaged => "SERVER_MANAGED",
            Self::SignalV1 => "SIGNAL_V1",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PROTOCOL_UNSPECIFIED" => Some(Self::Unspecified),
            "FANCY_V1_POST_JOIN" => Some(Self::FancyV1PostJoin),
            "FANCY_V1_FULL_ARCHIVE" => Some(Self::FancyV1FullArchive),
            "SERVER_MANAGED" => Some(Self::ServerManaged),
            "SIGNAL_V1" => Some(Self::SignalV1),
            _ => None,
        }
    }
}
