// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FilesEnvelope {
    #[prost(oneof = "files_envelope::Body", tags = "1, 2, 3, 4, 5, 6, 7, 8, 9, 10")]
    pub body: ::core::option::Option<files_envelope::Body>,
}
/// Nested message and enum types in `FilesEnvelope`.
pub mod files_envelope {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Body {
        #[prost(message, tag = "1")]
        Upload(super::UploadRequest),
        #[prost(message, tag = "2")]
        Download(super::DownloadRequest),
        #[prost(message, tag = "3")]
        Grant(super::Grant),
        #[prost(message, tag = "4")]
        Share(super::Share),
        #[prost(message, tag = "5")]
        Listing(super::Listing),
        #[prost(message, tag = "6")]
        List(super::ListRequest),
        #[prost(message, tag = "7")]
        Refused(super::Refused),
        #[prost(message, tag = "8")]
        Manage(super::ManageRequest),
        #[prost(message, tag = "9")]
        Managed(super::ManageListing),
        #[prost(message, tag = "10")]
        Forget(super::ForgetRequest),
    }
}
/// "My shared files", and the operator's view of the same table.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ManageRequest {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(enumeration = "Audience", tag = "2")]
    pub audience: i32,
    #[prost(uint32, tag = "3")]
    pub limit: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ManagedFile {
    #[prost(string, tag = "1")]
    pub key: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub channel: u32,
    #[prost(string, tag = "3")]
    pub filename: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub content_type: ::prost::alloc::string::String,
    #[prost(uint64, tag = "5")]
    pub size: u64,
    #[prost(enumeration = "Visibility", tag = "6")]
    pub visibility: i32,
    #[prost(uint64, tag = "7")]
    pub shared_at_ms: u64,
    /// `0` for a share with no lifetime.
    #[prost(uint64, tag = "8")]
    pub expires_at_ms: u64,
    /// When it was last read, or `0` if it never has been.
    #[prost(uint64, tag = "9")]
    pub downloaded_at_ms: u64,
    /// The link, for a share that has one.
    #[prost(string, tag = "10")]
    pub share_url: ::prost::alloc::string::String,
    /// Who shared it, in terms that outlive their connection. `account` is `0`
    /// for a guest, and `cert` empty for a client that presented none.
    #[prost(uint64, tag = "11")]
    pub uploader_account: u64,
    #[prost(string, tag = "12")]
    pub uploader_name: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "13")]
    pub uploader_cert: ::prost::alloc::vec::Vec<u8>,
    /// Whether that person is connected right now, so a dashboard can say so.
    #[prost(bool, tag = "14")]
    pub uploader_online: bool,
}
/// What the server holds, for the header of an operator's view.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Storage {
    #[prost(uint64, tag = "1")]
    pub used_bytes: u64,
    /// `0` where the operator set no ceiling.
    #[prost(uint64, tag = "2")]
    pub max_total_bytes: u64,
    #[prost(uint64, tag = "3")]
    pub max_upload_bytes: u64,
    #[prost(uint64, tag = "4")]
    pub file_count: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ManageListing {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub files: ::prost::alloc::vec::Vec<ManagedFile>,
    /// Only filled for `AUDIENCE_EVERYONE`: a user's own files say nothing about
    /// the server's disk.
    #[prost(message, optional, tag = "3")]
    pub storage: ::core::option::Option<Storage>,
}
/// Remove one stored file, rows and bytes together.
///
/// Your own needs no permission. Anyone else's needs `ResetUserContent` on the
/// root, which is murmur's bit for removing another person's content.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ForgetRequest {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub key: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UploadRequest {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub channel: u32,
    #[prost(string, tag = "3")]
    pub filename: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub content_type: ::prost::alloc::string::String,
    #[prost(uint64, tag = "5")]
    pub size: u64,
    #[prost(bytes = "vec", tag = "6")]
    pub sha256: ::prost::alloc::vec::Vec<u8>,
    #[prost(enumeration = "Visibility", tag = "7")]
    pub visibility: i32,
    /// How long the share should last, in seconds. `0` means it never expires,
    /// which is also what an upload that says nothing gets.
    #[prost(uint64, tag = "9")]
    pub ttl_seconds: u64,
    /// The password for a `VISIBILITY_PASSWORD` share, and nothing otherwise.
    ///
    /// Sent once, on the control connection, and never stored: the server keeps
    /// an Argon2id hash to check against, and derives the file's encryption key
    /// from the same secret. Losing the password loses the file.
    #[prost(string, tag = "8")]
    pub password: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DownloadRequest {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub key: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Grant {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub url: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub method: ::prost::alloc::string::String,
    #[prost(uint64, tag = "4")]
    pub expires_at_ms: u64,
    #[prost(string, tag = "5")]
    pub key: ::prost::alloc::string::String,
    /// Where this object will answer to anyone holding the link, once the bytes
    /// are in. Empty for a session share, which has no such address.
    ///
    /// Carried here rather than built by the client because the address is the
    /// server's to state: it is the operator's `public_url`, which the client
    /// never sees, and it does not expire the way `url` does.
    #[prost(string, tag = "6")]
    pub share_url: ::prost::alloc::string::String,
    /// When the finished share stops answering, or `0` for never.
    ///
    /// Distinct from `expires_at_ms` above, which is the moment this URL stops
    /// being spendable: one is the life of the link, the other the life of the
    /// file. The server's number rather than the client's arithmetic, so every
    /// reader agrees about when it goes.
    #[prost(uint64, tag = "7")]
    pub share_expires_at_ms: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Share {
    #[prost(string, tag = "1")]
    pub key: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub channel: u32,
    #[prost(uint32, tag = "3")]
    pub owner: u32,
    #[prost(string, tag = "4")]
    pub filename: ::prost::alloc::string::String,
    #[prost(uint64, tag = "5")]
    pub size: u64,
    #[prost(uint64, tag = "6")]
    pub shared_at_ms: u64,
    /// Reachable by link at all. Kept as the coarse question every reader had
    /// before there were two ways of answering it; `visibility` says which.
    #[prost(bool, tag = "7")]
    pub public: bool,
    #[prost(enumeration = "Visibility", tag = "8")]
    pub visibility: i32,
    /// The link, for a share that has one. Empty otherwise.
    #[prost(string, tag = "9")]
    pub share_url: ::prost::alloc::string::String,
    /// When this share stops answering, or `0` for never.
    #[prost(uint64, tag = "10")]
    pub expires_at_ms: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListRequest {
    #[prost(uint32, tag = "1")]
    pub channel: u32,
    #[prost(uint32, tag = "2")]
    pub limit: u32,
    #[prost(string, tag = "3")]
    pub before_key: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Listing {
    #[prost(uint32, tag = "1")]
    pub channel: u32,
    #[prost(message, repeated, tag = "2")]
    pub files: ::prost::alloc::vec::Vec<Share>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Refused {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub refusal: ::core::option::Option<crate::proto::fancy::wire::Refusal>,
}
/// Whose files a management listing is about.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Audience {
    /// The caller's own uploads, wherever they were shared. Needs no permission
    /// beyond being the person who uploaded them.
    Mine = 0,
    /// Every file on the server, for an operator. Needs `Write` on the root.
    Everyone = 1,
}
impl Audience {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Mine => "AUDIENCE_MINE",
            Self::Everyone => "AUDIENCE_EVERYONE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "AUDIENCE_MINE" => Some(Self::Mine),
            "AUDIENCE_EVERYONE" => Some(Self::Everyone),
            _ => None,
        }
    }
}
/// Who may reach a shared file.
///
/// One axis, three points, ordered by how far the file travels. `SESSION` is
/// zero because it is what an upload that says nothing gets: a client too old
/// to know about this field asks for the narrowest sharing, never the widest.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Visibility {
    /// Only the people the share is announced to, each fetch signed for.
    Session = 0,
    /// Anyone holding the link, with no account and no signature.
    Public = 1,
    /// Anyone holding the link who also knows the password.
    Password = 2,
}
impl Visibility {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Session => "VISIBILITY_SESSION",
            Self::Public => "VISIBILITY_PUBLIC",
            Self::Password => "VISIBILITY_PASSWORD",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "VISIBILITY_SESSION" => Some(Self::Session),
            "VISIBILITY_PUBLIC" => Some(Self::Public),
            "VISIBILITY_PASSWORD" => Some(Self::Password),
            _ => None,
        }
    }
}
