// This file is @generated by prost-build.
/// Keyset pagination over a UUIDv7-ordered store. Used by every fetch that
/// pages history: pchat Fetch, text HistoryRequest, audit Query, files
/// ListRequest all carry this trio by hand today and adopt Cursor at the M2
/// rewrite (docs/PROTOCOL-REDESIGN.md §9).
///
/// Keyset, not offset: an offset shifts under concurrent inserts and rescans
/// rows the store already paged past. UUIDv7 ids are time-ordered, so `before`
/// and `after` are stable positions for free.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Cursor {
    /// Return entries older than this id. Empty means "from the newest".
    #[prost(string, tag = "1")]
    pub before_id: ::prost::alloc::string::String,
    /// Return entries newer than this id. Empty means no lower bound.
    #[prost(string, tag = "2")]
    pub after_id: ::prost::alloc::string::String,
    /// Capped server-side; the cap is the server's, not the client's.
    #[prost(uint32, tag = "3")]
    pub limit: u32,
}
/// The tail of a page, so a client knows whether and where to continue.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PageInfo {
    #[prost(bool, tag = "1")]
    pub more: bool,
    /// Pass as Cursor.before_id of the next request.
    #[prost(string, tag = "2")]
    pub next_before_id: ::prost::alloc::string::String,
}
/// The coordinate every message-scoped feature shares: reactions, pins,
/// receipts, edits and deletes all address (channel, message).
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MessageRef {
    #[prost(uint32, tag = "1")]
    pub channel: u32,
    /// UUIDv7 as a string on the wire, 16 bytes in storage (docs/STORAGE.md L3).
    #[prost(string, tag = "2")]
    pub message_id: ::prost::alloc::string::String,
}
/// One emoji, either a Unicode grapheme cluster or a server-defined shortcode
/// ("mumble_parrot", no colons). A bare string cannot carry the distinction,
/// and both reactions (social) and custom-reaction config need it.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Emoji {
    #[prost(oneof = "emoji::Kind", tags = "1, 2")]
    pub kind: ::core::option::Option<emoji::Kind>,
}
/// Nested message and enum types in `Emoji`.
pub mod emoji {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Kind {
        #[prost(string, tag = "1")]
        Unicode(::prost::alloc::string::String),
        #[prost(string, tag = "2")]
        Shortcode(::prost::alloc::string::String),
    }
}
/// Why a request did not happen, in a shape a client can act on rather than
/// only display. Moderation's Refused, files' Refused and the throttle notice
/// each carry a fragment of this today.
///
/// Machine-readable kind first, prose second: the kind decides client
/// behaviour (re-auth, back off, give up), the detail is for the human.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Refusal {
    #[prost(enumeration = "refusal::Kind", tag = "1")]
    pub kind: i32,
    #[prost(string, tag = "2")]
    pub detail: ::prost::alloc::string::String,
    /// Only meaningful for RATE_LIMITED; zero elsewhere.
    #[prost(uint32, tag = "3")]
    pub retry_after_ms: u32,
}
/// Nested message and enum types in `Refusal`.
pub mod refusal {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Kind {
        /// Catch-all; detail carries the story.
        Other = 0,
        /// The actor lacks a permission. Retrying unchanged is pointless.
        Permission = 1,
        /// A server-side ceiling was met (history depth, listener count, size).
        Limit = 2,
        /// The request itself was malformed or referenced something unknown.
        Invalid = 3,
        /// Rate-limited; retry_after_ms says when it is worth trying again.
        RateLimited = 4,
    }
    impl Kind {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Other => "OTHER",
                Self::Permission => "PERMISSION",
                Self::Limit => "LIMIT",
                Self::Invalid => "INVALID",
                Self::RateLimited => "RATE_LIMITED",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "OTHER" => Some(Self::Other),
                "PERMISSION" => Some(Self::Permission),
                "LIMIT" => Some(Self::Limit),
                "INVALID" => Some(Self::Invalid),
                "RATE_LIMITED" => Some(Self::RateLimited),
                _ => None,
            }
        }
    }
}
