// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ScreenshareEnvelope {
    #[prost(oneof = "screenshare_envelope::Body", tags = "1, 2, 3, 4, 5, 6, 7")]
    pub body: ::core::option::Option<screenshare_envelope::Body>,
}
/// Nested message and enum types in `ScreenshareEnvelope`.
pub mod screenshare_envelope {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Body {
        #[prost(message, tag = "1")]
        Offer(super::Offer),
        #[prost(message, tag = "2")]
        Answer(super::Answer),
        #[prost(message, tag = "3")]
        Start(super::Start),
        #[prost(message, tag = "4")]
        Stop(super::Stop),
        #[prost(message, tag = "5")]
        Viewers(super::Viewers),
        #[prost(message, tag = "6")]
        Health(super::Health),
        #[prost(message, tag = "7")]
        Signal(super::WebRtcSignal),
    }
}
/// Epoch-0 type 120, which is the signalling this client speaks: one relayed
/// blob per step rather than a share with an identity. It is here, at inner tag
/// 7, because the alternative was worse in both directions - this client's whole
/// screen-share stack is built on it, and a canon with no home for it left
/// `canon.rs` returning `None`, which routes the feature down the
/// `PluginDataTransmission` relay. That relay works, and it is pure client-to-
/// client mesh: the server's SFU never sees a packet, so the one deployment that
/// needs an SFU - more than a couple of viewers - is the one that cannot have it.
///
/// The field numbers are murmur's `WebRtcSignal`, deliberately. The two are
/// separate messages in separate contracts and nothing requires them to agree,
/// but this client, the C++ fork and Starling all reason about the same four
/// fields, and a renumbering here would be a difference with no meaning behind
/// it.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WebRtcSignal {
    /// Who it is for; 0 means the sender's whole channel.
    #[prost(uint32, tag = "1")]
    pub target_session: u32,
    /// Who it is from. **Stamped by the server**, and whatever a client puts here
    /// is overwritten: a sender field a client fills is a client signalling as
    /// somebody else, which on this path means hijacking their broadcast.
    #[prost(uint32, tag = "2")]
    pub sender_session: u32,
    #[prost(enumeration = "web_rtc_signal::SignalType", tag = "3")]
    pub signal_type: i32,
    /// SDP for the offer and answer types, JSON for a candidate, empty otherwise.
    #[prost(string, tag = "4")]
    pub payload: ::prost::alloc::string::String,
}
/// Nested message and enum types in `WebRtcSignal`.
pub mod web_rtc_signal {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum SignalType {
        /// START is zero, which is murmur's numbering and therefore not negotiable.
        /// In proto3 that also makes it the value an absent field decodes to, so a
        /// signal with no type reads as START - exactly what murmur's `signal_type()`
        /// accessor returns for the same message, so the behaviour is unchanged.
        Start = 0,
        Stop = 1,
        SdpOffer = 2,
        SdpAnswer = 3,
        /// Accepted and dropped. The SFU is ICE-lite: it learns the peer's address
        /// from the incoming STUN binding requests and its own candidate rides in
        /// the answer, so a trickled candidate has nothing to do. This client
        /// already does not send them; a peer that does is not an error.
        IceCandidate = 4,
    }
    impl SignalType {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Start => "START",
                Self::Stop => "STOP",
                Self::SdpOffer => "SDP_OFFER",
                Self::SdpAnswer => "SDP_ANSWER",
                Self::IceCandidate => "ICE_CANDIDATE",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "START" => Some(Self::Start),
                "STOP" => Some(Self::Stop),
                "SDP_OFFER" => Some(Self::SdpOffer),
                "SDP_ANSWER" => Some(Self::SdpAnswer),
                "ICE_CANDIDATE" => Some(Self::IceCandidate),
                _ => None,
            }
        }
    }
}
/// The SFU is ICE-lite: it ignores trickled candidates and its own ride in the
/// answer. Never trickle ICE through the control plane - that is a contract
/// constraint, and each half of it cost a debugging session.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Offer {
    #[prost(string, tag = "1")]
    pub share_id: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub channel: u32,
    #[prost(string, tag = "3")]
    pub sdp: ::prost::alloc::string::String,
    /// Offers retry until answered, because the control plane rate-limits and a
    /// silently dropped offer looks exactly like a client bug.
    #[prost(uint32, tag = "4")]
    pub attempt: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Answer {
    #[prost(string, tag = "1")]
    pub share_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub sdp: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub sfu_host: ::prost::alloc::string::String,
    #[prost(uint32, tag = "4")]
    pub sfu_port: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Start {
    #[prost(string, tag = "1")]
    pub share_id: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub channel: u32,
    #[prost(uint32, tag = "3")]
    pub presenter: u32,
    #[prost(string, tag = "4")]
    pub title: ::prost::alloc::string::String,
    #[prost(uint32, tag = "5")]
    pub width: u32,
    #[prost(uint32, tag = "6")]
    pub height: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Stop {
    #[prost(string, tag = "1")]
    pub share_id: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub actor: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Viewers {
    #[prost(string, tag = "1")]
    pub share_id: ::prost::alloc::string::String,
    #[prost(uint32, repeated, tag = "2")]
    pub sessions: ::prost::alloc::vec::Vec<u32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Health {
    #[prost(string, tag = "1")]
    pub share_id: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub fps: u32,
    #[prost(uint32, tag = "3")]
    pub kbps: u32,
    #[prost(uint32, tag = "4")]
    pub dropped: u32,
}
