// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PermissionsEnvelope {
    #[prost(oneof = "permissions_envelope::Body", tags = "1, 2, 3, 4")]
    pub body: ::core::option::Option<permissions_envelope::Body>,
}
/// Nested message and enum types in `PermissionsEnvelope`.
pub mod permissions_envelope {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Body {
        #[prost(message, tag = "1")]
        Tokens(super::TokenSet),
        #[prost(message, tag = "2")]
        Invalidated(super::Invalidated),
        #[prost(message, tag = "3")]
        GroupQuery(super::GroupQuery),
        #[prost(message, tag = "4")]
        GroupList(super::GroupList),
    }
}
/// Access tokens are secrets a client presents to unlock ACL entries. Replacing
/// the whole set is deliberate: an incremental API would leave a client unable
/// to say "I have forgotten that one".
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TokenSet {
    #[prost(string, repeated, tag = "1")]
    pub tokens: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// The client's cached PermissionQuery answers are stale. Sent rather than left
/// implicit, because a stale grant in a UI is how a user learns about a
/// permission they no longer have by being refused mid-action.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Invalidated {
    #[prost(uint32, repeated, tag = "1")]
    pub channels: ::prost::alloc::vec::Vec<u32>,
    #[prost(bool, tag = "2")]
    pub everything: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GroupQuery {
    #[prost(uint32, tag = "1")]
    pub channel: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GroupList {
    #[prost(uint32, tag = "1")]
    pub channel: u32,
    #[prost(string, repeated, tag = "2")]
    pub groups: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MetadataEnvelope {
    #[prost(oneof = "metadata_envelope::Body", tags = "1, 2, 3, 4")]
    pub body: ::core::option::Option<metadata_envelope::Body>,
}
/// Nested message and enum types in `MetadataEnvelope`.
pub mod metadata_envelope {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Body {
        #[prost(message, tag = "1")]
        Extras(super::ChannelExtras),
        #[prost(message, tag = "2")]
        Structural(super::StructuralHint),
        #[prost(message, tag = "3")]
        Subscribe(super::Subscribe),
        #[prost(message, tag = "4")]
        Delta(super::SyncDelta),
    }
}
/// Fancy channel properties that upstream's ChannelState has no field for.
/// Upstream owns 1–99 in every upstream message; these live out here instead of
/// squatting on upstream's next field number, docs/PROTOCOL-COMPATIBILITY.md §1.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ChannelExtras {
    #[prost(uint32, tag = "1")]
    pub channel: u32,
    #[prost(uint32, tag = "2")]
    pub expiry_mode: u32,
    #[prost(uint32, tag = "3")]
    pub expiry_duration_s: u32,
    #[prost(uint64, tag = "4")]
    pub created_at_ms: u64,
    #[prost(uint64, tag = "5")]
    pub last_active_ms: u64,
    #[prost(bool, tag = "6")]
    pub hidden: bool,
    #[prost(bool, tag = "7")]
    pub structural: bool,
    #[prost(uint32, tag = "8")]
    pub pchat_protocol: u32,
    #[prost(uint32, tag = "9")]
    pub pchat_max_history: u32,
    #[prost(uint32, tag = "10")]
    pub pchat_retention_days: u32,
}
/// A structural channel is a grouping node no one can enter. Stock clients have
/// no idea, so they are told nothing and simply never see anyone in it.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StructuralHint {
    #[prost(uint32, repeated, tag = "1")]
    pub channels: ::prost::alloc::vec::Vec<u32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Subscribe {
    #[prost(uint32, repeated, tag = "1")]
    pub channels: ::prost::alloc::vec::Vec<u32>,
    #[prost(bool, tag = "2")]
    pub everything: bool,
}
/// A coalesced batch of state changes for a lazy subscriber, the delivery
/// half of Subscribe, and the mechanism that takes presence fan-out from
/// Θ(events × clients) to Θ(events × subscribers of the changed entity).
///
/// Legacy clients keep the murmur flood: one UserState broadcast to every
/// session per change. A subscribed Fancy client instead receives these, and
/// only for entities inside its subscription. The server MAY coalesce a burst
/// (a mass-move, a reconnect wave) into one delta; a client applies entries in
/// order and treats the batch as atomic.
///
/// The frames inside are *encoded upstream messages*, embedded as bytes. A
/// protobuf submessage and a bytes field share one wire shape (tag ‖ len ‖
/// payload), so the buffer encoded once for the legacy flood is placed here
/// verbatim, never re-encoded per recipient, and decoded by the parsers a
/// client already has (docs/PROTOCOL-REDESIGN.md §4, rule Z3).
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SyncDelta {
    /// Encoded MumbleProto.UserState frames, verbatim.
    #[prost(bytes = "vec", repeated, tag = "1")]
    pub user_states: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    /// Encoded MumbleProto.ChannelState frames, verbatim.
    #[prost(bytes = "vec", repeated, tag = "2")]
    pub channel_states: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    /// Sessions gone from the subscribed view. Deliberately one list: left the
    /// server, or moved somewhere unsubscribed, the render outcome is the same,
    /// and distinguishing them would leak movement the subscriber cannot see.
    #[prost(uint32, repeated, tag = "3")]
    pub users_gone: ::prost::alloc::vec::Vec<u32>,
    /// Channels removed from the subscribed view.
    #[prost(uint32, repeated, tag = "4")]
    pub channels_gone: ::prost::alloc::vec::Vec<u32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UserdataEnvelope {
    #[prost(oneof = "userdata_envelope::Body", tags = "1, 2, 3, 4, 5")]
    pub body: ::core::option::Option<userdata_envelope::Body>,
}
/// Nested message and enum types in `UserdataEnvelope`.
pub mod userdata_envelope {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Body {
        #[prost(message, tag = "1")]
        Action(super::AccountAction),
        #[prost(message, tag = "2")]
        Ack(super::AccountAck),
        #[prost(message, tag = "3")]
        Settings(super::Settings),
        #[prost(message, tag = "4")]
        SettingsUpdate(super::SettingsUpdate),
        #[prost(message, tag = "5")]
        SettingsQuery(super::SettingsQuery),
    }
}
/// The account self-service surface: everything a user may change about their
/// own account. Each carries the current password, because a hijacked session
/// must not be able to lock the owner out.
///
/// **Nothing here names an account.** The server resolves the caller's own from
/// the session the frame arrived on, so this is a surface that can only ever act
/// on the person using it; an id on the wire would be an id a client could
/// change.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AccountAction {
    #[prost(enumeration = "account_action::Kind", tag = "1")]
    pub kind: i32,
    #[prost(string, tag = "2")]
    pub current_password: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub value: ::prost::alloc::string::String,
    /// A code from the authenticator, when one is needed: confirming an
    /// enrolment, and proving the device is still in hand before TOTP comes off.
    #[prost(string, tag = "4")]
    pub totp: ::prost::alloc::string::String,
}
/// Nested message and enum types in `AccountAction`.
pub mod account_action {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Kind {
        /// Not an action, and the zero value on purpose.
        ///
        /// proto3 cannot distinguish an unset enum from its first value, so with
        /// `SET_PASSWORD = 0` a default-constructed message - a client that forgot
        /// the field, a decode of the wrong bytes - *was* a request to set the
        /// password to the empty string. The dangerous default has to be the one
        /// that means nothing.
        Unspecified = 0,
        SetPassword = 1,
        SetEmail = 2,
        Rename = 3,
        EnableTotp = 4,
        DisableTotp = 5,
        Unregister = 6,
    }
    impl Kind {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Unspecified => "UNSPECIFIED",
                Self::SetPassword => "SET_PASSWORD",
                Self::SetEmail => "SET_EMAIL",
                Self::Rename => "RENAME",
                Self::EnableTotp => "ENABLE_TOTP",
                Self::DisableTotp => "DISABLE_TOTP",
                Self::Unregister => "UNREGISTER",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "UNSPECIFIED" => Some(Self::Unspecified),
                "SET_PASSWORD" => Some(Self::SetPassword),
                "SET_EMAIL" => Some(Self::SetEmail),
                "RENAME" => Some(Self::Rename),
                "ENABLE_TOTP" => Some(Self::EnableTotp),
                "DISABLE_TOTP" => Some(Self::DisableTotp),
                "UNREGISTER" => Some(Self::Unregister),
                _ => None,
            }
        }
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AccountAck {
    #[prost(enumeration = "account_action::Kind", tag = "1")]
    pub kind: i32,
    #[prost(bool, tag = "2")]
    pub ok: bool,
    #[prost(string, tag = "3")]
    pub detail: ::prost::alloc::string::String,
    /// The new secret, base32 as an authenticator expects it. Sent **only** in
    /// answer to the first half of an ENABLE_TOTP, and never stored anywhere it
    /// can be read back: enrolment is not finished until a code derived from it
    /// comes back, so a client that loses this asks again and gets a new one
    /// rather than a locked account.
    #[prost(string, tag = "4")]
    pub totp_secret: ::prost::alloc::string::String,
}
/// This account's stored client settings.
///
/// Server to client. Sent in answer to a `SettingsQuery` and after every
/// `SettingsUpdate`, so the client's copy is always something the server said
/// rather than something the client assumed took effect.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Settings {
    #[prost(map = "string, string", tag = "1")]
    pub values: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SettingsUpdate {
    #[prost(map = "string, string", tag = "1")]
    pub set: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(string, repeated, tag = "2")]
    pub unset: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// "Send me my settings."
///
/// Explicit rather than implied by an empty `Settings`: a client and a server
/// that both use one message for the question and the answer eventually send it
/// to each other at the same time, and neither can tell which it received.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SettingsQuery {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerConfigEnvelope {
    #[prost(oneof = "server_config_envelope::Body", tags = "1, 2, 3")]
    pub body: ::core::option::Option<server_config_envelope::Body>,
}
/// Nested message and enum types in `ServerConfigEnvelope`.
pub mod server_config_envelope {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Body {
        #[prost(message, tag = "1")]
        Query(super::ConfigQuery),
        #[prost(message, tag = "2")]
        Values(super::ConfigValues),
        #[prost(message, tag = "3")]
        Update(super::ConfigUpdate),
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ConfigQuery {}
/// One editable setting: its current value, and everything a client needs to
/// render a field for it without knowing the key.
///
/// The schema travels with the value because the server is the only thing that
/// knows it. A client that hard-codes "max_users is an integer labelled Maximum
/// users" has to ship a release whenever an operator-facing knob is added, and
/// `Snapshot.extra` exists precisely so a service can add one without a proto
/// change; those would arrive as untyped, unlabelled keys and render as raw
/// strings, which is how a settings screen rots.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Setting {
    #[prost(string, tag = "1")]
    pub key: ::prost::alloc::string::String,
    #[prost(enumeration = "setting::Kind", tag = "2")]
    pub kind: i32,
    /// The section it belongs under, so a form groups without a lookup table.
    #[prost(string, tag = "3")]
    pub group: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub label: ::prost::alloc::string::String,
    /// **Empty when `secret`.** Those are write-only.
    #[prost(string, tag = "5")]
    pub value: ::prost::alloc::string::String,
    /// The permitted values. Meaningful for CHOICE, empty otherwise.
    #[prost(string, repeated, tag = "6")]
    pub options: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Never carries a value outward, and only ever received. Named rather than
    /// omitted, so a client can tell "no password set" from "password withheld",
    /// they mean very different things to whoever is looking at the screen.
    #[prost(bool, tag = "7")]
    pub secret: bool,
    #[prost(string, tag = "8")]
    pub help: ::prost::alloc::string::String,
}
/// Nested message and enum types in `Setting`.
pub mod setting {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Kind {
        String = 0,
        /// Multi-line: the welcome text is a paragraph, not a field.
        Text = 1,
        Bool = 2,
        Int = 3,
        Choice = 4,
    }
    impl Kind {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::String => "STRING",
                Self::Text => "TEXT",
                Self::Bool => "BOOL",
                Self::Int => "INT",
                Self::Choice => "CHOICE",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "STRING" => Some(Self::String),
                "TEXT" => Some(Self::Text),
                "BOOL" => Some(Self::Bool),
                "INT" => Some(Self::Int),
                "CHOICE" => Some(Self::Choice),
                _ => None,
            }
        }
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConfigValues {
    #[prost(message, repeated, tag = "1")]
    pub settings: ::prost::alloc::vec::Vec<Setting>,
    /// Monotonic. A client drops a snapshot older than the one it holds, which is
    /// what stops a slow reply from overwriting a fresh edit.
    #[prost(uint64, tag = "2")]
    pub version: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConfigUpdate {
    #[prost(map = "string, string", tag = "1")]
    pub values: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
