#include "markdown_highlighter.h"

#include <QTextCharFormat>
#include <QtQml/qqml.h>

// Generated by cxx-qt-build from src/bridge.rs: MdSpan + md_line_spans.
// (The .cxxqt.h wrapper must be the entry point - it resolves the circular
// include with bridge.cxx.h in the right order.)
#include "qt6ui/src/bridge.cxxqt.h"

namespace {

// Span flag bits - keep in sync with fancy_utils::markdown::flags.
constexpr quint16 kBold = 1;
constexpr quint16 kItalic = 2;
constexpr quint16 kUnderline = 4;
constexpr quint16 kStrike = 8;
constexpr quint16 kCode = 16;
constexpr quint16 kLink = 32;
constexpr quint16 kSpoiler = 64;
constexpr quint16 kMention = 128;
constexpr quint16 kFenceMarker = 256;

// Colors mirroring themes/dark.css (same values as the `theme` object in
// qml/main.qml).
const QColor kAccent(0x2a, 0xab, 0xee);
const QColor kStrikeText(255, 255, 255, 179);      // white @ 70% (mdStrike opacity)
const QColor kMuted(255, 255, 255, 89);            // --color-text-muted (35%)
const QColor kCodeBg(255, 255, 255, 20);           // --color-glass-hover (8%)
const QColor kSpoilerBg(255, 255, 255, 31);        // mdSpoiler (12%)
const QColor kMentionBg(0x2a, 0xab, 0xee, 38);     // mdMention (accent 15%)
const QColor kLinkUnderline(0x2a, 0xab, 0xee, 102); // mdLink underline (accent 40%)

QStringList monospaceFamilies()
{
    return {QStringLiteral("JetBrains Mono"), QStringLiteral("Fira Code"),
            QStringLiteral("Consolas"), QStringLiteral("monospace")};
}

// Fenced-code block state carried between text blocks.
constexpr int kStateInFence = 1;

} // namespace

MarkdownHighlighter::MarkdownHighlighter(QObject *parent)
    : QSyntaxHighlighter(parent)
{
}

void MarkdownHighlighter::setTextDocument(QQuickTextDocument *doc)
{
    if (doc == m_textDocument)
        return;
    m_textDocument = doc;
    setDocument(doc ? doc->textDocument() : nullptr);
    Q_EMIT textDocumentChanged();
}

void MarkdownHighlighter::highlightBlock(const QString &text)
{
    const bool inFence = previousBlockState() == kStateInFence;
    bool outFence = inFence;

    const QByteArray utf8 = text.toUtf8();
    const rust::Vec<MdSpan> spans =
        md_line_spans(rust::Str(utf8.constData(), static_cast<size_t>(utf8.size())),
                      inFence, outFence);
    setCurrentBlockState(outFence ? kStateInFence : 0);

    for (const MdSpan &span : spans) {
        QTextCharFormat fmt;
        if (span.flags & kBold)
            fmt.setFontWeight(QFont::Bold);
        if (span.flags & kItalic)
            fmt.setFontItalic(true);
        if (span.flags & kUnderline)
            fmt.setFontUnderline(true);
        if (span.flags & kStrike) {
            fmt.setFontStrikeOut(true);
            fmt.setForeground(kStrikeText);
        }
        if (span.flags & kCode) {
            fmt.setFontFamilies(monospaceFamilies());
            fmt.setBackground(kCodeBg);
        }
        if (span.flags & kLink) {
            fmt.setForeground(kAccent);
            fmt.setFontUnderline(true);
            fmt.setUnderlineColor(kLinkUnderline);
        }
        if (span.flags & kSpoiler)
            fmt.setBackground(kSpoilerBg);
        if (span.flags & kMention) {
            fmt.setForeground(kAccent);
            fmt.setBackground(kMentionBg);
        }
        if (span.flags & kFenceMarker) {
            fmt.setFontFamilies(monospaceFamilies());
            fmt.setForeground(kMuted);
        }
        setFormat(span.start, span.len, fmt);
    }
}

extern "C" void qt6ui_register_qml_types()
{
    qmlRegisterType<MarkdownHighlighter>("com.fancymumble.qt6ui", 1, 0, "MarkdownHighlighter");
}
