//! Minimal, low-RAM native Qt 6 (QML) client for `mumble-protocol`.
//!
//! All client logic (connection, chat, channel roster, audio) lives in the
//! reused workspace crates; this binary only wires a QML front-end onto the
//! [`Backend`](bridge::qobject::Backend) QObject via cxx-qt.
//!
//! On Windows a console window would otherwise pop up; `windows_subsystem`
//! suppresses it for release builds.
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

mod app;
mod bridge;
mod constants;
mod events;
mod i18n;
mod mode;
mod profile;
mod store;

use cxx_qt_lib::{QGuiApplication, QQmlApplicationEngine, QUrl};

unsafe extern "C" {
    /// Registers the hand-written C++ QML types (MarkdownHighlighter);
    /// defined in `cpp/markdown_highlighter.cpp`.
    fn qt6ui_register_qml_types();
}

fn main() {
    // rustls refuses to guess when several crypto providers are compiled in;
    // without this the first TLS connect panics (and takes the app down).
    // Same fix as mumble-tauri/src/lib.rs.
    let _ = rustls::crypto::ring::default_provider().install_default();

    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| tracing_subscriber::EnvFilter::new("warn,qt6ui=info")),
        )
        .init();

    // Full hardware-accelerated QtQuick by default (~88 MB RSS on Windows).
    // Users who want to trade GPU rendering for ~30 MB less RAM can set
    // `QT_QUICK_BACKEND=software` in the environment.

    let mut app = QGuiApplication::new();

    // Hand-written C++ QML types must be registered before the engine
    // instantiates the module.
    unsafe { qt6ui_register_qml_types() };

    let mut engine = QQmlApplicationEngine::new();

    if let Some(engine) = engine.as_mut() {
        // Resource path generated by cxx-qt-build for the QmlModule whose URI
        // is `com.fancymumble.qt6ui` and which lists `qml/main.qml`.
        engine.load(&QUrl::from(
            "qrc:/qt/qml/com/fancymumble/qt6ui/qml/main.qml",
        ));
    }

    if let Some(app) = app.as_mut() {
        app.exec();
    }
}
