// Centralised icon barrel.
//
// All icons are re-exported from `lucide-react` (https://lucide.dev) under
// the legacy display names previously used by the per-file
// `assets/icons/*.svg?react` imports. This means consumer components can
// keep using `<MicIcon />` etc. without any JSX changes - only the import
// line needs to point at this barrel.
//
// To add a new icon, look it up at https://lucide.dev/icons and add a
// re-export here. Lucide ships ~1500 icons (MIT, actively maintained), so
// it should be the only icon source going forward - please do not add any
// more inline SVGs or per-icon asset files.

export {
  Activity as ActivityIcon,
  AudioWaveform as AudioWaveformIcon,
  SlidersHorizontal as SlidersIcon,
  Sparkles as SparklesIcon,
  GripVertical as GripVerticalIcon,
  Paperclip as AttachIcon,
  FileText as FileTextIcon,
  Palette as PaletteIcon,
  PaintBucket as PaintBucketIcon,
  ArrowUpRight as ArrowUpRightIcon,
  Bell as BellIcon,
  BellOff as BellOffIcon,
  Ban as BlockIcon,
  SquareCheck as CheckboxIcon,
  CheckCheck as CheckDoubleIcon,
  Check as CheckIcon,
  Check as CheckSingleIcon,
  ChevronDown as ChevronDownIcon,
  ChevronLeft as ChevronLeftIcon,
  ChevronRight as ChevronRightIcon,
  X as CloseIcon,
  Copy as CopyIcon,
  Database as DatabaseIcon,
  Pencil as EditIcon,
  SmilePlus as EmojiPlusIcon,
  CircleAlert as ErrorCircleIcon,
  Folder as FolderIcon,
  Minimize as FullscreenExitIcon,
  Maximize as FullscreenIcon,
  FileImage as GifIcon,
  Grid2x2 as Grid2x2Icon,
  Hash as HashIcon,
  Headphones as HeadphonesIcon,
  HeadphoneOff as HeadphonesOffIcon,
  Image as ImageIcon,
  Info as InfoFilledIcon,
  Info as InfoIcon,
  EllipsisVertical as KebabMenuIcon,
  Key as KeyIcon,
  Keyboard as KeyboardIcon,
  Ear as ListenBadgeIcon,
  Lock as LockIcon,
  Lock as LockSvg,
  LogOut as LogoutIcon,
  Maximize2 as MaximizeIcon,
  Menu as MenuIcon,
  MessageSquare as MessageIcon,
  MessageSquareOff as MessageMinusIcon,
  Mic as MicIcon,
  MicOff as MicOffIcon,
  MicOff as MicOffSmallIcon,
  Minus as MinimizeIcon,
  Moon as MoonIcon,
  Pause as PauseIcon,
  PictureInPicture2 as PopoutIcon,
  Phone as PhoneIcon,
  PhoneOff as PhoneOffIcon,
  Play as PlayIcon,
  Plus as PlusIcon,
  ChartBar as PollIcon,
  Quote as QuoteIcon,
  Disc as RecordIcon,
  RefreshCw as RefreshCwIcon,
  RotateCw as RefreshIcon,
  ScreenShare as ScreenShareIcon,
  Search as SearchIcon,
  Send as SendIcon,
  Server as ServerIcon,
  Settings as SettingsIcon,
  ShieldCheck as ShieldCheckIcon,
  ShieldCheck as ShieldCheckSvg,
  Shield as ShieldIcon,
  Star as StarIcon,
  File as FileIcon,
  Trash2 as TrashIcon,
  UserRound as UserFilledIcon,
  User as UserIcon,
  UserPlus as UserPlusIcon,
  Users as UsersGroupIcon,
  UserX as UserXIcon,
  Volume2 as VolumeIcon,
  VolumeX as VolumeOffIcon,
  TriangleAlert as WarningFilledIcon,
  TriangleAlert as WarningIcon,
  TriangleAlert as WarningSvg,
  X as WindowCloseIcon,
  MessageCircle as MessageCircleIcon,
  AlignLeft as AlignLeftIcon,
  AlignCenter as AlignCenterIcon,
  AlignRight as AlignRightIcon,
  AlignJustify as AlignJustifyIcon,
  Undo2 as UndoIcon,
  Redo2 as RedoIcon,
  Minus as MinusIcon,
  List as ListIcon,
  ArrowLeft as ArrowLeftIcon,
  ArrowRight as ArrowRightIcon,
  ArrowUp as ArrowUpIcon,
  ArrowDown as ArrowDownIcon,
  Newspaper as NewspaperIcon,
  FileDown as FileDownIcon,
  History as HistoryIcon,
  Share2 as ShareIcon,
  Printer as PrinterIcon,
  Globe as GlobeIcon,
  Puzzle as PuzzleIcon,
  Store as StoreIcon,
  Download as DownloadIcon,
  Power as PowerIcon,
  Pin as PinIcon,
  Shuffle as ShuffleIcon,
  Hand as HandIcon,
  Link as LinkIcon,
  Pilcrow as PilcrowIcon,
  Indent as IndentIcon,
  Outdent as OutdentIcon,
  Circle as CircleIcon,
  CircleDot as CircleDotIcon,
  Square as SquareIcon,
} from "lucide-react";
